package in.handyman.raven.lib;

import in.handyman.raven.exception.HandymanException;
import in.handyman.raven.lambda.access.ResourceAccess;
import in.handyman.raven.lambda.action.ActionExecution;
import in.handyman.raven.lambda.action.IActionExecution;
import in.handyman.raven.lambda.doa.audit.ActionExecutionAudit;
import in.handyman.raven.lib.custom.outbound.dao.PredictionDTO;
import in.handyman.raven.lib.custom.outbound.model.CustomResponseOutputTable;
import in.handyman.raven.lib.model.CustomResponseGeneration;
import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

import static in.handyman.raven.core.enums.DatabaseConstants.DB_INSERT_WRITE_BATCH_SIZE;
import static in.handyman.raven.core.enums.DatabaseConstants.DB_SELECT_READ_BATCH_SIZE;

/**
 * Auto Generated By Raven
 */
@ActionExecution(
    actionName = "CustomResponseGeneration"
)
public class CustomResponseGenerationAction implements IActionExecution {
  private final ActionExecutionAudit action;

  private final Logger log;

  private final CustomResponseGeneration customResponseGeneration;

  private final Marker aMarker;

  public CustomResponseGenerationAction(final ActionExecutionAudit action, final Logger log,
      final Object customResponseGeneration) {
    this.customResponseGeneration = (CustomResponseGeneration) customResponseGeneration;
    this.action = action;
    this.log = log;
    this.aMarker = MarkerFactory.getMarker(" CustomResponseGeneration:"+this.customResponseGeneration.getName());
  }

  @Override
  public void execute() throws Exception {
    try {
      ResourceAccess.rdbmsJDBIConn(customResponseGeneration.getResourceConn());
      log.info(aMarker, "Custom Response generation Action for {} has been started", customResponseGeneration.getName());

      final String insertQuery =
              "INSERT INTO " + customResponseGeneration.getResultTable() +
                      " (process_id, group_id, origin_id, custom_response, tenant_id, root_pipeline_id, " +
                      " status, stage, message, feature, triggered_url, batch_id, inbound_transaction_id, " +
                      " created_on, last_updated_on) " +
                      " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

      final List<URL> urls = Optional.ofNullable(action.getContext().get("custom.response.generation.consumer.url"))
              .map(s -> Arrays.stream(s.split(",")).map(s1 -> {
                try {
                  return new URL(s1.trim());
                } catch (MalformedURLException e) {
                  throw new HandymanException("Malformed URL: " + s1, e, action);
                }
              }).collect(Collectors.toList()))
              .orElse(Collections.singletonList(new URL("http://localhost/")));

      final CoproProcessor<PredictionDTO, CustomResponseOutputTable> coproProcessor =
              new CoproProcessor<>(new LinkedBlockingQueue<>(),
                      CustomResponseOutputTable.class,
                      PredictionDTO.class,
                      customResponseGeneration.getResourceConn(),
                      log,
                      new PredictionDTO(),
                      urls,
                      action);

      int readBatchSize = Integer.parseInt(action.getContext().getOrDefault(DB_SELECT_READ_BATCH_SIZE, "10"));
      int writeBatchSize = Integer.parseInt(action.getContext().getOrDefault(DB_INSERT_WRITE_BATCH_SIZE, "10"));
      int consumerCount = Integer.parseInt(action.getContext().getOrDefault("custom.response.generation.consumer.API.count", "1"));

      coproProcessor.startProducer(customResponseGeneration.getQuerySet(), readBatchSize);
      Thread.sleep(1000);
      CoproProcessor.ConsumerProcess<PredictionDTO, CustomResponseOutputTable> consumerProcess =
              new CustomResponseGenerationConsumerProcessor(log, aMarker, action);
      coproProcessor.startConsumer(insertQuery, consumerCount, writeBatchSize, consumerProcess);
      log.info(aMarker, "Custom Response generation Action has been completed {}  ", customResponseGeneration.getName());

    } catch (Exception e) {
      action.getContext().put(customResponseGeneration.getName() + ".isSuccessful", "false");
      log.error(aMarker, "Error in execute method for Multi value concatenation ", e);
      HandymanException handymanException = new HandymanException(e);
      HandymanException.insertException("Multi value concatenation failed ", handymanException, action);
    }

  }

  @Override
  public boolean executeIf() throws Exception {
    return customResponseGeneration.getCondition();
  }
}
