package in.handyman.raven.lib;

import in.handyman.raven.core.encryption.SecurityEngine;
import in.handyman.raven.core.encryption.inticsgrity.InticsIntegrity;
import in.handyman.raven.exception.HandymanException;
import in.handyman.raven.lambda.access.ResourceAccess;
import in.handyman.raven.lambda.action.ActionExecution;
import in.handyman.raven.lambda.action.IActionExecution;
import in.handyman.raven.lambda.doa.audit.ActionExecutionAudit;
import in.handyman.raven.lib.model.DocumentWisePostProcessing;
import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import in.handyman.raven.lib.model.DocumentWisePostProcessingInput;
import in.handyman.raven.lib.model.scalar.ValidationByDocumentWiseExecutor;
import in.handyman.raven.util.CommonQueryUtil;
import org.jdbi.v3.core.Handle;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.core.statement.PreparedBatch;
import org.slf4j.Logger;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

import static in.handyman.raven.core.enums.EncryptionConstants.ENCRYPT_ITEM_WISE_ENCRYPTION;

/**
 * Auto Generated By Raven
 */
@ActionExecution(
    actionName = "DocumentWisePostProcessing"
)
public class DocumentWisePostProcessingAction implements IActionExecution {
  private final ActionExecutionAudit action;

  private final Logger log;

  private final DocumentWisePostProcessing documentWisePostProcessing;

  private final Marker aMarker;

  private List<DocumentWisePostProcessingInput> documentWisePostProcessingInputs;

  private static final String DOCUMENT_WISE_POST_PROCESSING_THREAD_COUNT = "document.wise.post.processing.thread.count";

  public DocumentWisePostProcessingAction(final ActionExecutionAudit action, final Logger log,
                                          final Object documentWisePostProcessing) {
    this.documentWisePostProcessing = (DocumentWisePostProcessing) documentWisePostProcessing;
    this.action = action;
    this.log = log;
    this.aMarker = MarkerFactory.getMarker("DocumentWisePostProcessing:" + this.documentWisePostProcessing.getName());
  }

  @Override
  public void execute() throws Exception {
    Jdbi jdbi = ResourceAccess.rdbmsJDBIConn(documentWisePostProcessing.getResourceConn());
    InticsIntegrity crypt = SecurityEngine.getInticsIntegrityMethod(action, log);
    String itemWiseEncryptionActivator = action.getContext().getOrDefault(ENCRYPT_ITEM_WISE_ENCRYPTION, "true");
    int threadCount = Integer.parseInt(action.getContext().getOrDefault(DOCUMENT_WISE_POST_PROCESSING_THREAD_COUNT, "10"));

    boolean encryptEnabled = Boolean.parseBoolean(itemWiseEncryptionActivator);
    log.info(aMarker, "DocumentWisePostProcessing started with encryptEnabled: {}", encryptEnabled);

    action.getContext().put("resource.conn", documentWisePostProcessing.getResourceConn());

    jdbi.useTransaction(handle -> fetchAndDecryptInputs(handle, crypt, encryptEnabled));

    log.info(aMarker, "Fetched {} records for document-wise post-processing", documentWisePostProcessingInputs.size());
    String outputTable = documentWisePostProcessing.getOutputTable();
    documentWisePostProcessingInputs = new ValidationByDocumentWiseExecutor(documentWisePostProcessingInputs, action, log, threadCount, outputTable).doDocumentWiseValidator();
    log.info(aMarker, "Total records present after document-wise post-processing: {}", documentWisePostProcessingInputs.size());

    documentWisePostProcessingInputs.forEach(input -> processEncryption(input, crypt, encryptEnabled));

    log.info(aMarker, "Processing completed. Results were inserted into {} by CoproProcessor", outputTable);
  }

  private void fetchAndDecryptInputs(Handle handle, InticsIntegrity crypt, boolean encryptEnabled) {
    List<String> queries = CommonQueryUtil.getFormattedQuery(documentWisePostProcessing.getQuerySet());
    documentWisePostProcessingInputs = queries.stream()
            .flatMap(sql -> handle.createQuery(sql)
                    .mapToBean(DocumentWisePostProcessingInput.class)
                    .stream())
            .collect(Collectors.toList());
    log.info(aMarker, "Total records fetched: {}", documentWisePostProcessingInputs.size());

    if (encryptEnabled) {
      log.info(aMarker, "Decrypting only encrypted values before BSH processing");
      String scalarAdapterActivator = action.getContext().getOrDefault("scalar.adapter.activator", "false");

      documentWisePostProcessingInputs.forEach(input -> {
        if (input.getPredictedValue() != null && !input.getPredictedValue().isEmpty()
                && input.getIsEncrypted()) {
          try {
            String encryptionPolicy = input.getEncryptionPolicy() != null && !input.getEncryptionPolicy().isEmpty()
                ? input.getEncryptionPolicy()
                : ("false".equalsIgnoreCase(scalarAdapterActivator) ? "AES256" : "AES256");
            log.debug(aMarker, "Using encryption policy: {}", encryptionPolicy);

            String itemIdentifier = input.getSorItemName() != null ? input.getSorItemName() : String.valueOf(input.getSorItemId());
            String decryptedValue = crypt.decrypt(input.getPredictedValue(), encryptionPolicy, itemIdentifier);
            input.setPredictedValue(decryptedValue);
            log.debug(aMarker, "Decrypted value for sorItemId: {}", input.getSorItemId());
          } catch (Exception e) {
            log.warn(aMarker, "Failed to decrypt value for sorItemId: {}, using encrypted value. Error: {}",
                    input.getSorItemId(), e.getMessage());
          }
        } else {
          log.debug(aMarker, "Skipping decryption for sorItemId: {} (isEncrypted: {})",
                  input.getSorItemId(), input.getIsEncrypted());
        }
      });

      long decryptedCount = documentWisePostProcessingInputs.stream()
              .filter(DocumentWisePostProcessingInput::getIsEncrypted)
              .count();
      log.info(aMarker, "Decrypted {} out of {} records", decryptedCount, documentWisePostProcessingInputs.size());
    }
  }

  private void processEncryption(DocumentWisePostProcessingInput input, InticsIntegrity crypt, boolean encryptEnabled) {
    if (encryptEnabled && input.getPredictedValue() != null && !input.getPredictedValue().isEmpty()
            && input.getIsEncrypted()) {
      try {
        String encryptionPolicy = input.getEncryptionPolicy() != null && !input.getEncryptionPolicy().isEmpty()
            ? input.getEncryptionPolicy() : "AES256";

        String itemIdentifier = input.getSorItemName() != null ? input.getSorItemName() : String.valueOf(input.getSorItemId());
        input.setPredictedValue(crypt.encrypt(input.getPredictedValue(), encryptionPolicy, itemIdentifier));
        log.debug(aMarker, "Re-encrypted value for sorItemId: {} with policy: {}", input.getSorItemId(), encryptionPolicy);
      } catch (Exception e) {
        log.warn(aMarker, "Failed to encrypt value for sorItemId: {}. Error: {}",
                input.getSorItemId(), e.getMessage());
      }
    } else {
      log.debug(aMarker, "Skipping encryption for sorItemId: {} (isEncrypted: {})",
              input.getSorItemId(), input.getIsEncrypted());
    }
  }

  @Override
  public boolean executeIf() throws Exception {
    return documentWisePostProcessing.getCondition();
  }
}
