package in.handyman.raven.lib;

import in.handyman.raven.lambda.action.ActionExecution;
import in.handyman.raven.lambda.action.IActionExecution;
import in.handyman.raven.lambda.doa.audit.ActionExecutionAudit;
import in.handyman.raven.lib.model.Documentparser;
import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import org.slf4j.Logger;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

/**
 * Auto Generated By Raven
 */
@ActionExecution(
    actionName = "Documentparser"
)
public class DocumentparserAction implements IActionExecution {
  private final ActionExecutionAudit action;

  private final Logger log;

  private final Documentparser documentparser;

  private final Marker aMarker;

  public DocumentparserAction(final ActionExecutionAudit action, final Logger log,
      final Object documentparser) {
    this.documentparser = (Documentparser) documentparser;
    this.action = action;
    this.log = log;
    this.aMarker = MarkerFactory.getMarker(" Documentparser:"+this.documentparser.getName());
  }

  @Override
  public void execute() throws Exception {
  }

  @Override
  public boolean executeIf() throws Exception {
    return documentparser.getCondition();
  }
}
