package in.handyman.raven.lib;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
import in.handyman.raven.exception.HandymanException;
import in.handyman.raven.lambda.access.ResourceAccess;
import in.handyman.raven.lambda.action.ActionExecution;
import in.handyman.raven.lambda.action.IActionExecution;
import in.handyman.raven.lambda.doa.audit.ActionExecutionAudit;
import in.handyman.raven.lib.model.LocalDirectoryfileTransfer;

import java.io.File;
import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.file.*;
import java.nio.file.attribute.FileTime;
import java.sql.Types;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.*;
import java.util.stream.Collectors;

import jakarta.json.Json;
import org.jdbi.v3.core.Handle;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.core.argument.Arguments;
import org.jdbi.v3.core.argument.NullArgument;
import org.slf4j.Logger;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;


import java.nio.file.attribute.BasicFileAttributes;

/**
 * Auto Generated By Raven
 */
@ActionExecution(
    actionName = "LocalDirectoryfileTransferAction"
)
public class LocalDirectoryfileTransferAction implements IActionExecution {
  private final ActionExecutionAudit action;

  private final Logger log;

  private final LocalDirectoryfileTransfer localDirectoryfileTransfer;

  private final Marker aMarker;


  public LocalDirectoryfileTransferAction(final ActionExecutionAudit action, final Logger log,
                                          final Object localDirectoryfileTransferAction) {
    this.localDirectoryfileTransfer = (LocalDirectoryfileTransfer) localDirectoryfileTransferAction;
    this.action = action;
    this.log = log;
    this.aMarker = MarkerFactory.getMarker(" LocalDirectoryfileTransferAction:"+this.localDirectoryfileTransfer.getName());

  }

  @Override
  public void execute() throws Exception {

    log.info(aMarker, "localDirectoryfileTransferAction Action has been started {}",localDirectoryfileTransfer.getName());

    final Jdbi jdbi = ResourceAccess.rdbmsJDBIConn(localDirectoryfileTransfer.getResourceConn());
    jdbi.getConfig(Arguments.class).setUntypedNullArgument(new NullArgument(Types.NULL));
    log.info(aMarker, "Local directory file transfer  Action output table {}",localDirectoryfileTransfer.getResultTable());

//    final List<URL> urls = Optional.ofNullable(action.getContext().get("alchemy.outbound.kvp.url")).map(s -> Arrays.stream(s.split(",")).map(s1 -> {
//      try {
//        return new URL(s1);
//      } catch (MalformedURLException e) {
//        log.error("Error in processing the URL ", e);
//        throw new HandymanException("Error in processing the URL", e, action);
//      }
//    }).collect(Collectors.toList())).orElse(Collections.emptyList());
//    log.info(aMarker, "local directory file transfer urls {}", urls);




//    final Long id= Long.valueOf(action.getContext().get("15"));
//    final Long id = action.getContext().get();

//    final Long tenantId= Long.valueOf(action.getContext().get("15"));
    // file paths
    final String sourceFilePath = localDirectoryfileTransfer.getSourceDirectory();
    final String destinationPath=localDirectoryfileTransfer.getDestinationDirectoryPath();
//    final Long rootpipelineId =action.getRootPipelineId();

//    final String processTime=action.getContext().get("2023-10-06T14:30:00");
    final String processTime="2023-10-06T14:30:00";
    LocalDateTime uploadedTime= LocalDateTime.parse(processTime);


    // Create a Path object
    Path sourcePath = Paths.get(sourceFilePath);
    Path targetFolder=Paths.get(destinationPath);
    boolean directoryExists = false;
    String message="";


    LocalFileTransferTable data = new LocalFileTransferTable();





    // Check if the file or directory exists
    if (Files.exists(sourcePath)) {
//      fileExists = true;
     log.info("File or directory exists");

      // Check if it's a directory
      if (Files.isDirectory(sourcePath)) {
        directoryExists = true;


        log.info("The specified path is a directory.");




          if (Files.isReadable(sourcePath)) {


            // we need to create directory for the file only when we can access the file

            if(Files.exists(targetFolder)) {
              log.info("target directory exists");

            }else{
              Files.createDirectory(targetFolder);
              log.info("target directory not exists hence created");

            }
              log.info("file is readable");

              DirectoryStream<Path> stream = Files.newDirectoryStream(sourcePath);
              for (Path file : stream) {
                BasicFileAttributes attributes = Files.readAttributes(file, BasicFileAttributes.class);
                FileTime creationTime = attributes.creationTime();
                LocalDateTime creationDateTime = LocalDateTime.ofInstant(creationTime.toInstant(), ZoneId.systemDefault());

                String fileName = file.getFileName().toString();
                Path targetFilePath= Path.of(targetFolder + File.separator + fileName);
                  // targetFolder= Path.of(targetFolder );
                  // Initialize ObjectMapper







                  ObjectMapper objectMapper = new ObjectMapper();
                  JsonNodeFactory nodeFactory = objectMapper.getNodeFactory();



                  if(uploadedTime==null){
                      // Serialize the filteredFiles list to JSON

                      ArrayNode filteredFilesArray = nodeFactory.arrayNode();
                      filteredFilesArray.add(String.valueOf(file));
                      ObjectNode dataNode = objectMapper.valueToTree(data); // Convert data to JSON object
                        dataNode.set("directoryFileList", filteredFilesArray);
                      data = objectMapper.treeToValue(dataNode, LocalFileTransferTable.class);

                      Files.copy(file,targetFolder);
                  log.info("Files are transferrd successfully");
                  message="Files are transferrd successfully";
                    data.setMessage(message);
                }else{
                      ArrayNode filteredFilesArray = nodeFactory.arrayNode();
                      creationDateTime.isAfter(uploadedTime);
                      filteredFilesArray.add(String.valueOf(file.toAbsolutePath()));
                      String filteredFilesJson = objectMapper.writeValueAsString(filteredFilesArray);
//                      data.setDirectoryFileList(Collections.singletonList(filteredFilesJson));



                      Files.copy(file,targetFilePath, StandardCopyOption.REPLACE_EXISTING);
                  log.info("Files are transferrd successfully");
                    message="Files are transferrd successfully";
                    data.setMessage(message);
                }


              }





            final String insertQuery="INSERT INTO "+ localDirectoryfileTransfer.getResultTable()
                    + "(root_pipeline_id, tenant_id, id, last_processed_on, message, isdirectoryexists, directory_filelist, sourcepath, destinationpath)"+
                    " VALUES(:rootPipelineId, :tenantId, :id, :lastProcessedOn, :message, :isdirectoryexists, :directoryFileList, :sourceDirectoryPath, :destinationDirectoryPath)";

              data.setId(Long.valueOf(7));
              data.setTenantId(Long.valueOf(8));
              data.setSourceDirectoryPath(sourceFilePath);
              data.setDestinationDirectoryPath(destinationPath);
              data.setRootPipelineId(3);
              data.setLastProcessedOn(LocalDateTime.now());
              data.setIsdirectoryexists(directoryExists);




                    // open JDBI connection and start insert

            try (Handle handle = jdbi.open()) {
              handle.createUpdate(insertQuery)
                      .bindBean(data)
                      .execute();
              log.info(aMarker, "Data inserted successfully");
              message="Data inserted successfully";
              data.setMessage(message);
            } catch (Exception e) {
              log.error("Error inserting data: " + e.getMessage());
                    throw new Exception();
            }


          }else{
            log.info("file can't be accessed");
            message="can't be accessed";
            data.setMessage(message);
          }
      }else {
        message="file is not a directory";
        log.info("file is not a directory");
        data.setMessage(message);
      }



    }else {
      message="no directory exists";
      log.info("no directory exists");
      data.setMessage(message);
    }





    }

  @Override
  public boolean executeIf () throws Exception {
    return localDirectoryfileTransfer.getCondition();
  }
}
