package in.handyman.raven.lib;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import in.handyman.raven.core.encryption.SecurityEngine;
import in.handyman.raven.core.encryption.impl.EncryptionRequestClass;
import in.handyman.raven.core.encryption.inticsgrity.InticsIntegrity;
import in.handyman.raven.exception.HandymanException;
import in.handyman.raven.lambda.access.ResourceAccess;
import in.handyman.raven.lambda.action.ActionExecution;
import in.handyman.raven.lambda.action.IActionExecution;
import in.handyman.raven.lambda.doa.audit.ActionExecutionAudit;
import in.handyman.raven.lib.model.MultivalueSorItemHandling;
import in.handyman.raven.lib.services.soritemhandling.MultiValueOutputResult;
import in.handyman.raven.lib.services.soritemhandling.MultivalueSorItemHandlingActionInput;
import in.handyman.raven.util.CommonQueryUtil;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.core.result.ResultIterable;
import org.jdbi.v3.core.statement.Query;
import org.slf4j.Logger;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import static in.handyman.raven.core.enums.EncryptionConstants.ENCRYPT_ITEM_WISE_ENCRYPTION;
import static in.handyman.raven.core.enums.EncryptionConstants.KVP_JSON_PARSER_ENCRYPTION;

/**
 * Auto Generated By Raven
 */
@ActionExecution(actionName = "MultivalueSorItemHandling")
public class MultivalueSorItemHandlingAction implements IActionExecution {
    private final ActionExecutionAudit action;

    private final Logger log;

    private final MultivalueSorItemHandling multivalueSorItemHandling;
    static ObjectMapper objectMapper = new ObjectMapper();
    private static final Set<String> MEMBER_GROUPING_KEYS = Set.of("memberId", "memberName", "memberDob");

    private final Marker aMarker;
    public static final String AES_256 = "AES256";
    private static final Pattern TRAILING_NUMBER = Pattern.compile("_(\\d+)$");

    public MultivalueSorItemHandlingAction(final ActionExecutionAudit action, final Logger log, final Object multivalueSorItemHandling) {
        this.multivalueSorItemHandling = (MultivalueSorItemHandling) multivalueSorItemHandling;
        this.action = action;
        this.log = log;
        this.aMarker = MarkerFactory.getMarker(" MultivalueSorItemHandling:" + this.multivalueSorItemHandling.getName());
    }

    // Assuming this is part of a class that has access to log, aMarker, action, encryption, etc.

    @Override
    public void execute() throws Exception {

        // --- Initial Setup and Input Fetching ---
        final Jdbi jdbi = ResourceAccess.rdbmsJDBIConn(multivalueSorItemHandling.getResourceConn());
        InticsIntegrity encryption = SecurityEngine.getInticsIntegrityMethod(action, log);

        // Check if item-wise encryption is globally active for the pipeline
        String pipelineEndToEndEncryptionActivatorStr = action.getContext().get(ENCRYPT_ITEM_WISE_ENCRYPTION);
        boolean pipelineEndToEndEncryptionActivator = Boolean.parseBoolean(pipelineEndToEndEncryptionActivatorStr);

        // Check if KVP-specific fields (Labels, Alias) are configured for encryption
        String kvpJsonParserEncryptionStr = action.getContext().get(KVP_JSON_PARSER_ENCRYPTION);
        boolean kvpJsonParserEncryptionActivator = Boolean.parseBoolean(kvpJsonParserEncryptionStr);

        String outputTableName = multivalueSorItemHandling.getOutputTable();
        // This list will be the input for the filtering logic
        final List<MultivalueSorItemHandlingActionInput> tableInfos = fetchValuesFromDB(jdbi);

        log.info(aMarker, "Starting Multi value concatenation process. Input records fetched: {}", tableInfos.size());

        try {

            // =================================================================
            // STEP 1: DECRYPTION
            // Decrypt incoming data if pipeline encryption is active.
            // =================================================================
//            if (pipelineEndToEndEncryptionActivator) {
//                log.info(aMarker, "DECRYPTION: Pipeline encryption is active. Decrypting data fields...");
//
//                // Decrypt answers (conditional based on isEncrypted flag in each record)
//                decryptAnswers(tableInfos, encryption);
//
//                if (kvpJsonParserEncryptionActivator) {
//                    decryptSectionAlias(tableInfos, encryption);
//                }
//            }

            // =================================================================
            // STEP 2: CORE PROCESSING (Filtering, Consolidation, Mapping)
            // (Assuming a method exists that does the filtering and returns the final mapped list)
            // Note: The logic from your previous query should run here.
            // We'll rename the variable to better reflect the processed list.
            // =================================================================
            log.info(aMarker, "PROCESSING: Executing filtering and consolidation logic.");

            // NOTE: You would replace this placeholder with the actual complex filtering and mapping logic.
            // For demonstration, we assume a method that processes the decrypted 'tableInfos'
            // and returns the final list ready for encryption/insertion.
            List<MultiValueOutputResult> updatedTableInfos = processAndMapFilteredData(tableInfos);

            // =================================================================
            // STEP 3: ENCRYPTION
            // Encrypt outgoing data fields if pipeline encryption is active.
            // =================================================================
//            if (pipelineEndToEndEncryptionActivator) {
//                log.info(aMarker, "ENCRYPTION: Pipeline encryption is 365active. Encrypting data fields...");
//
//                // Encrypt answers (conditional based on isEncrypted flag in each record)
//                encryptAnswers(updatedTableInfos, encryption);
//
//                if (kvpJsonParserEncryptionActivator) {
//                    // Encrypt Labels and Section Alias (conditional based on KVP flag)
//                    encryptLabels(updatedTableInfos, encryption);
////                    encryptSectionAlias(updatedTableInfos, encryption);
//                }
//            }

            // =================================================================
            // STEP 4: INSERT FINAL OUTPUT
            // =================================================================
            outputBuilderAndInsert(jdbi, outputTableName, updatedTableInfos);

            log.info(aMarker, "Successfully inserted {} records into {}", updatedTableInfos.size(), outputTableName);

        } catch (Exception e) {
            log.error(aMarker, "Error in execute method for Multi value concatenation ", e);
            HandymanException handymanException = new HandymanException(e);
            HandymanException.insertException("Multi value concatenation failed ", handymanException, action);
            throw handymanException;
        }
    }

    /**
     * Executes the complex filtering and consolidation logic (Cases 1, 3, 4) on the decrypted
     * input data, then maps the retained records to the final MultiValueOutputResult structure.
     *
     * @param inputList The full list of decrypted records fetched from the database.
     * @return A list of MultiValueOutputResult objects ready for encryption and insertion.
     */
    public List<MultiValueOutputResult> processAndMapFilteredData(List<MultivalueSorItemHandlingActionInput> inputList) throws Exception {

        log.info(aMarker, "Starting core business logic filtering and consolidation. Input size: {}", inputList.size());

        // --- 1. Separate inputs based on Line Item Type ---
        Map<String, List<MultivalueSorItemHandlingActionInput>> groupedByType = inputList.stream().collect(Collectors.groupingBy(MultivalueSorItemHandlingActionInput::getLineItemType));

        // Exclude 'multiple_member_indicator' items from the main flow
        List<MultivalueSorItemHandlingActionInput> nonIndicatorInputs = inputList.stream().filter(item -> !"multiple_member_indicator".equals(item.getSorItemName())).collect(Collectors.toList());

        // Separate based on the main line item types
        List<MultivalueSorItemHandlingActionInput> multiValueInputs = nonIndicatorInputs.stream().filter(item -> "multi_value".equals(item.getLineItemType())).collect(Collectors.toList());

        List<MultivalueSorItemHandlingActionInput> singleValueInputs = nonIndicatorInputs.stream().filter(item -> "single_value".equals(item.getLineItemType())).collect(Collectors.toList());

        List<MultivalueSorItemHandlingActionInput> multiMemberKeyFilteredList = inputList.stream().filter(item -> "multiple_member_indicator".equals(item.getSorItemName())).collect(Collectors.toList());

        // --- Accumulate results from all cases ---
        List<MultivalueSorItemHandlingActionInput> consolidatedInputs = new ArrayList<>();

        // =================================================================
        // CASE 1: Multi-Value Items (De-duplication)
        // =================================================================
        List<MultivalueSorItemHandlingActionInput> case1Output = handleCase1MultiValue(multiValueInputs, aMarker, log);
        consolidatedInputs.addAll(case1Output);
        log.info(aMarker, "Processed Case 1 (Multi-Value). Retained: {}", case1Output.size());

        // =================================================================
        // Cases 2, 3, 4: Single-Value Items
        // =================================================================
        if (!singleValueInputs.isEmpty()) {

            // --- Initial Section Alias Filtering (Case 2/Filter 1) ---
            // This method handles the whitelisting priority/score fallback, returning only the chosen winner for each SorItemName.
            List<MultivalueSorItemHandlingActionInput> maxSingleValueFilteredList = filterBySectionAliasOrFallback(singleValueInputs);
            log.info(aMarker, "Processed Initial Filter (Section Alias). Retained: {}", maxSingleValueFilteredList.size());


            // --- Split for Multi-Entity Handling ---
            Map<Boolean, List<MultivalueSorItemHandlingActionInput>> groupedByMultiEntity = maxSingleValueFilteredList.stream().collect(Collectors.partitioningBy(item -> "true".equalsIgnoreCase(item.getIsMultiEntityEnabled())));

            List<MultivalueSorItemHandlingActionInput> multiEntityEnabledList = groupedByMultiEntity.get(true);
            List<MultivalueSorItemHandlingActionInput> multiEntityDisabledList = groupedByMultiEntity.get(false);

            // --- Execute Case 3 Logic (Multi-Entity Enabled) ---
            // This is handled via the consolidation logic in handleCase3.
            List<MultivalueSorItemHandlingActionInput> case3Output = handleCase3MultiEntityEnabled(multiEntityEnabledList, aMarker, log, action);
            consolidatedInputs.addAll(case3Output);
            log.info(aMarker, "Processed Case 3 (Multi-Entity Enabled). Retained: {}", case3Output.size());

            // --- Execute Case 4 Logic (Multi-Entity Disabled Consolidation) ---
            List<MultivalueSorItemHandlingActionInput> case4Output = handleCase4MultiEntityDisabled(multiEntityDisabledList, aMarker, log, action);
            consolidatedInputs.addAll(case4Output);
            log.info(aMarker, "Processed Case 4 (Multi-Entity Disabled). Retained: {}", case4Output.size());
        }

        // --- Process the 'multiple_member_indicator' keys (Case 2/Filter 2) ---
        // These keys are treated as simple single-value items (no complex consolidation needed).
        handleSingleValueLineItems(multiMemberKeyFilteredList, false, null, consolidatedInputs);

        log.info(aMarker, "Filtering and consolidation complete. Total consolidated inputs: {}", consolidatedInputs.size());


        // =================================================================
        // STEP 5: FINAL MAPPING AND FILTERING
        // =================================================================
        List<MultiValueOutputResult> finalOutput = new ArrayList<>();

        for (MultivalueSorItemHandlingActionInput inputItem : consolidatedInputs) {

            // Only convert items that were NOT removed during filtering/consolidation.
            if (!inputItem.isRemovedAfterFiltering()) {

                // Map the retained input item to the final output structure
                MultiValueOutputResult outputResult = mapInputToOutput(inputItem);

                finalOutput.add(outputResult);
            } else {
                // Retaining removed items for audit purpose if needed, but not adding to final output.
                // We ensure the message is logged/available for auditing the pipeline's decision.
                log.debug(aMarker, "Filtered out item: {}. Message: {}", inputItem.getSorItemName(), inputItem.getMessage());
            }
        }

        log.info(aMarker, "Mapping complete. Final records ready for encryption: {}", finalOutput.size());
        return finalOutput;
    }


    public void handleSingleValueLineItems(List<MultivalueSorItemHandlingActionInput> inputList, boolean pipelineEndToEndEncryptionActivator, InticsIntegrity encryption, // This is the corrected parameter type/name
                                           List<MultivalueSorItemHandlingActionInput> consolidatedInputs) { // Changed output type for accumulation

        if (inputList == null || inputList.isEmpty()) {
            log.info(aMarker, "handleSingleValueLineItems received an empty list, skipping processing.");
            return;
        }

        log.info(aMarker, "Starting processing for {} simple single-value items/indicators.", inputList.size());

        // NOTE: If the output list needs to be MultiValueOutputResult, the type should be
        // List<MultiValueOutputResult>. Assuming here it is MultivalueSorItemHandlingActionInput
        // since it accumulates into consolidatedInputs in the calling method.

        // Check KVP encryption flag for labels/alias: Retrieve this from the class field (action)
        // assuming ENCRYPT_ITEM_WISE_ENCRYPTION and KVP_JSON_PARSER_ENCRYPTION are constants available.
        String kvpJsonParserEncryptionStr = action.getContext().get(KVP_JSON_PARSER_ENCRYPTION);
        boolean kvpJsonParserEncryptionActivator = Boolean.parseBoolean(kvpJsonParserEncryptionStr);


        // 1. Prepare inputs for insertion/encryption (No filtering, just setting audit fields)
        List<MultiValueOutputResult> currentBatch = new ArrayList<>();
        for (MultivalueSorItemHandlingActionInput inputItem : inputList) {

            // Ensure the items are marked as retained
            inputItem.setRemovedAfterFiltering(false);
            inputItem.setMessage("Retained by simple single-value handling (e.g., indicator key).");

            // NOTE: Since the main encryption happens later on the finalOutput list,
            // this method should only perform the logic if the entire pipeline is structured to
            // handle encryption at this step. Given your overall pipeline flow, it's safer
            // to map and encrypt LATER in Step 5 of the main method.

            // --- Revised Logic: Map and Encrypt LATER ---
            // Instead of processing encryption here, we just add the processed input item
            // to the list for later unified mapping and encryption (in STEP 5).
            consolidatedInputs.add(inputItem);
        }

        // Since we changed the final encryption logic to happen in STEP 5,
        // the conditional encryption block is now redundant here and is removed.
        // The items are simply added to the consolidatedInputs list.

        log.info(aMarker, "Finished processing simple single-value items. Added {} records to consolidated inputs.", inputList.size());
    }

    public void outputBuilderAndInsert(Jdbi jdbi, String outputTable, List<MultiValueOutputResult> outputs) {
        if (outputs.isEmpty()) {
            log.info(aMarker, "No records to insert into {}", outputTable);
            return;
        }

        // --- UPDATED SQL to include new columns ---
        String sql = "INSERT INTO " + outputTable + " (sor_item_name, answer, b_box, group_id, batch_id, category, document_id, line_item_type, model_id, model_info, model_registry, origin_id, paper_no, question_id, sor_item_attribution_id, root_pipeline_id, score, sor_question, stage, status, synonym_id, tenant_id, vqa_score, is_encrypted, encryption_policy_id, encryption_policy,sor_container_instance, is_removed_after_filtering, message, section_priority_after_filter, created_on, last_updated_on) VALUES (:sorItemName, :answer, :BBox, :groupId, :batchId, :category, :documentId, :lineItemType, " +
                  ":modelId, :modelInfo, :modelRegistry, :originId, :paperNo, :questionId, :sorItemAttributionId, " +
                ":rootPipelineId, :score, :sorQuestion, :stage, :status, :synonymId, :tenantId, :vqaScore, :isEncrypted, " +
                ":encryptionPolicyId, :encryptionPolicy, :sorContainerInstance, :isRemovedAfterFiltering, :message, " +
                ":sectionPriorityAfterFilter, :createdOn, :lastUpdatedOn )";


        jdbi.useHandle(handle -> {
            var batch = handle.prepareBatch(sql);
            for (MultiValueOutputResult output : outputs) {
                batch
                        .bind("sorItemName",output.getSorItemName())
                        .bind("answer",output.getAnswer())
                        .bind("BBox",output.getBBox())
                        .bind("groupId",output.getGroupId())
                        .bind("batchId",output.getBatchId())
                        .bind("category",output.getCategory())
                        .bind("documentId",output.getDocumentId())
                        .bind("lineItemType",output.getLineItemType())
                        .bind("modelId",output.getModelId())
                        .bind("modelInfo",output.getModelInfo())
                        .bind("modelRegistry",output.getModelRegistry())
                        .bind("originId",output.getOriginId())
                        .bind("paperNo",output.getPaperNo())
                        .bind("questionId",output.getQuestionId())
                        .bind("sorItemAttributionId",output.getSorItemAttributionId())
                        .bind("rootPipelineId",output.getRootPipelineId())
                        .bind("score",output.getScore())
                        .bind("sorQuestion",output.getSorQuestion())
                        .bind("stage",output.getStage())
                        .bind("status",output.getStatus())
                        .bind("synonymId",output.getSynonymId())
                        .bind("tenantId",output.getTenantId())
                        .bind("vqaScore",output.getVqaScore())
                        .bind("isEncrypted",output.getIsEncrypted())
                        .bind("encryptionPolicyId",output.getEncryptionPolicyId())
                        .bind("encryptionPolicy",output.getEncryptionPolicy())
                        .bind("sorContainerInstance",output.getSorContainerInstance())
                        .bind("isRemovedAfterFiltering", output.isRemovedAfterFiltering())
                        .bind("message", output.getMessage())
                        .bind("sectionPriorityAfterFilter", output.getSectionPriorityAfterFilter())
                        .bind("createdOn", java.time.LocalDateTime.now())
                        .bind("lastUpdatedOn", java.time.LocalDateTime.now())
                        .add();
            }

            int[] result = batch.execute();
            log.info(aMarker, "Inserted {} records into {}", result.length, outputTable);
        });
    }

    /**
     * Helper method to map MultivalueSorItemHandlingActionInput to MultiValueOutputResult,
     * including the new audit columns.
     */
    private MultiValueOutputResult mapInputToOutput(MultivalueSorItemHandlingActionInput inputItem) {
        // NOTE: This assumes MultiValueOutputResult has matching fields and structure to the input,
        // which is common for transformation steps.
        MultiValueOutputResult output = new MultiValueOutputResult();

        // Map all common fields
        output.setAnswer(inputItem.getAnswer());
        output.setBBox(inputItem.getBBox());
        output.setDocumentId(inputItem.getDocumentId());
        output.setGroupId(inputItem.getGroupId());
        output.setBatchId(inputItem.getBatchId());
        output.setCategory(inputItem.getCategory());
        output.setLineItemType(inputItem.getLineItemType());
        output.setModelId(inputItem.getModelId());
        output.setModelInfo(inputItem.getModelInfo());
        output.setModelRegistry(inputItem.getModelRegistry());
        output.setOriginId(inputItem.getOriginId());
        output.setPaperNo(inputItem.getPaperNo());
        output.setQuestionId(inputItem.getQuestionId());
        output.setRootPipelineId(inputItem.getRootPipelineId());
        output.setScore(inputItem.getScore());
        output.setSorItemAttributionId(inputItem.getSorItemAttributionId());
        output.setSorItemName(inputItem.getSorItemName());
        output.setSorQuestion(inputItem.getSorQuestion());
        output.setStage(inputItem.getStage());
        output.setStatus(inputItem.getStatus());
        output.setSynonymId(inputItem.getSynonymId());
        output.setTenantId(inputItem.getTenantId());
        output.setVqaScore(inputItem.getVqaScore());
        output.setIsEncrypted(Boolean.valueOf(inputItem.getIsEncrypted()));
        output.setEncryptionPolicyId(inputItem.getEncryptionPolicyId());
        output.setEncryptionPolicy(inputItem.getEncryptionPolicy());
        output.setSorContainerInstance(inputItem.getSorContainerInstance());

        // Map the three new audit/filter columns
        output.setRemovedAfterFiltering(inputItem.isRemovedAfterFiltering());
        output.setMessage(inputItem.getMessage());
        output.setSectionPriorityAfterFilter(inputItem.getSectionPriorityAfterFilter());

        return output;
    }

    public List<MultivalueSorItemHandlingActionInput> filterBySectionAliasOrFallback(List<MultivalueSorItemHandlingActionInput> inputs) {
        if (inputs == null || inputs.isEmpty()) {
            return Collections.emptyList();
        }

        ObjectMapper mapper = new ObjectMapper();
        List<MultivalueSorItemHandlingActionInput> finalOutput = new ArrayList<>();

        // -------------------------------
        // Group base: originId → paperNo → sorContainerInstance
        // -------------------------------
        Map<String, Map<Long, Map<String, List<MultivalueSorItemHandlingActionInput>>>> grouped = inputs.stream().collect(Collectors.groupingBy(MultivalueSorItemHandlingActionInput::getOriginId, Collectors.groupingBy(MultivalueSorItemHandlingActionInput::getPaperNo, Collectors.groupingBy(MultivalueSorItemHandlingActionInput::getSorContainerInstance))));

        // Process each instance group
        for (String originId : grouped.keySet()) {
            for (Long paperNo : grouped.get(originId).keySet()) {
                for (String instance : grouped.get(originId).get(paperNo).keySet()) {

                    List<MultivalueSorItemHandlingActionInput> instanceList = grouped.get(originId).get(paperNo).get(instance);

                    // For priority selection
                    int bestPriority = Integer.MAX_VALUE;
                    List<MultivalueSorItemHandlingActionInput> bestMatches = new ArrayList<>();

                    for (MultivalueSorItemHandlingActionInput item : instanceList) {

                        String rawJson = item.getWhitelistedSections();
                        String alias = item.getSectionAlias();

                        if (rawJson == null || alias == null) {
                            continue;
                        }

                        try {
                            List<Map<String, Object>> parsed = mapper.readValue(rawJson, new TypeReference<List<Map<String, Object>>>() {
                            });

                            for (Map<String, Object> entry : parsed) {
                                String truthEntity = (String) entry.get("truthEntity");
                                Integer priority = (Integer) entry.get("priorityLevel");

                                if (truthEntity == null || priority == null) continue;

                                // contains-match (case insensitive)
                                if (alias.toLowerCase().contains(truthEntity.toLowerCase())) {

                                    if (priority < bestPriority) { // smaller = higher priority
                                        bestPriority = priority;
                                        bestMatches.clear();
                                        bestMatches.add(item);
                                    } else if (priority == bestPriority) {
                                        bestMatches.add(item);
                                    }
                                }
                            }

                        } catch (Exception e) {
                            // ignore JSON parse errors for this entry
                            log.info(aMarker, "Error parsing whitelistedSections JSON for item {}: {}", item.getSorItemName(), e.getMessage());
                        }
                    }

                    // If at least one priority-based match exists
                    if (!bestMatches.isEmpty()) {
                        finalOutput.addAll(bestMatches);
                    }
                }
            }
        }

        // -------------------------------
        // If priority-based filtering returned something → apply max-group logic
        // -------------------------------
        if (!finalOutput.isEmpty()) {
            return selectMaxCountNodes(finalOutput);
        }

        // -------------------------------
        // Priority returned ZERO → fallback
        // -------------------------------
        return selectMaxCountNodes(inputs);
    }


    public List<MultivalueSorItemHandlingActionInput> processMultivalueSorItems(List<MultivalueSorItemHandlingActionInput> multivalueConcatenationInputs, Marker aMarker, Logger log, ActionExecutionAudit action) throws Exception {

        log.info(aMarker, "Starting Multivalue SOR Item processing. Total input records: {}", multivalueConcatenationInputs.size());

        // --- 1. Separate inputs based on Line Item Type ---
        Map<String, List<MultivalueSorItemHandlingActionInput>> groupedByType = multivalueConcatenationInputs.stream().collect(Collectors.groupingBy(MultivalueSorItemHandlingActionInput::getLineItemType));

        List<MultivalueSorItemHandlingActionInput> multiValueInputs = groupedByType.getOrDefault("multi_value", Collections.emptyList());
        List<MultivalueSorItemHandlingActionInput> singleValueInputs = groupedByType.getOrDefault("single_value", Collections.emptyList());

        // --- Final Output List (Accumulates results from all cases) ---
        List<MultivalueSorItemHandlingActionInput> finalFilteredOutput = new ArrayList<>();

        // =================================================================
        // CASE 1: Multi-Value Items (De-duplication)
        // =================================================================
        List<MultivalueSorItemHandlingActionInput> case1Output = handleCase1MultiValue(multiValueInputs, aMarker, log);
        finalFilteredOutput.addAll(case1Output);

        // =================================================================
        // CASE 2, 3, 4: Single-Value Items (Requires complex filtering)
        // =================================================================
        if (!singleValueInputs.isEmpty()) {

            // --- Split Single Value Inputs based on Multi-Entity Flag ---
            Map<Boolean, List<MultivalueSorItemHandlingActionInput>> groupedByMultiEntity = singleValueInputs.stream().collect(Collectors.partitioningBy(item -> "true".equalsIgnoreCase(item.getIsMultiEntityEnabled())));

            List<MultivalueSorItemHandlingActionInput> multiEntityEnabledList = groupedByMultiEntity.get(true);
            List<MultivalueSorItemHandlingActionInput> multiEntityDisabledList = groupedByMultiEntity.get(false);

            // --- Execute Case 3 Logic ---
            List<MultivalueSorItemHandlingActionInput> case3Output = handleCase3MultiEntityEnabled(multiEntityEnabledList, aMarker, log, action);
            finalFilteredOutput.addAll(case3Output);

            // --- Execute Case 4 Logic (Includes sub-logic for consolidation) ---
            List<MultivalueSorItemHandlingActionInput> case4Output = handleCase4MultiEntityDisabled(multiEntityDisabledList, aMarker, log, action);
            finalFilteredOutput.addAll(case4Output);
        }

        log.info(aMarker, "Finished all processing stages. Total consolidated records: {}", finalFilteredOutput.size());
        return finalFilteredOutput;
    }

    /**
     * CASE 1: Process all 'multi_value' line items, performing normalization (splitting comma-separated values)
     * and then de-duplication.
     * * @param multiValueInputs The list of multi_value records fetched from the database.
     *
     * @param aMarker The audit marker.
     * @param log     The logger.
     * @return A list containing unique, normalized multi_value records (along with the original, split records for audit).
     */
    private List<MultivalueSorItemHandlingActionInput> handleCase1MultiValue(List<MultivalueSorItemHandlingActionInput> multiValueInputs, Marker aMarker, Logger log) {

        log.info(aMarker, "CASE 1: Processing {} multi_value records.", multiValueInputs.size());

        // Step 1: Normalization (Split comma-separated answers into new records)
        List<MultivalueSorItemHandlingActionInput> normalizedList = new ArrayList<>();
        String delimiter = ",";

        for (MultivalueSorItemHandlingActionInput item : multiValueInputs) {
            String answer = item.getAnswer();

            if (answer != null && answer.contains(delimiter)) {
                String[] values = answer.split(delimiter);

                // Mark the original item as removed/transformed
                item.setRemovedAfterFiltering(true);
                item.setMessage(String.format("Split and removed due to multiple values (%s). Individual values will be processed.", item.getSorItemName()));

                int splitCount = 0;
                for (String singleValue : values) {
                    String trimmedValue = singleValue.trim();
                    if (!trimmedValue.isEmpty()) {
                        // Clone the object for the single, trimmed value
                        MultivalueSorItemHandlingActionInput newItem = cloneInputItem(item); // Assumes cloneHelper method exists
                        newItem.setAnswer(trimmedValue);
                        newItem.setRemovedAfterFiltering(false); // Reset for the new item
                        newItem.setMessage(String.format("Normalized from a multi-value"));

                        normalizedList.add(newItem);
                        splitCount++;
                    }
                }
                log.debug(aMarker, "Split item {} into {} new records.", item.getSorItemName(), splitCount);

            } else {
                // Keep the original item if no splitting occurred
                normalizedList.add(item);
            }
        }

        log.info(aMarker, "Normalization complete. List size expanded from {} to {}.", multiValueInputs.size(), normalizedList.size());


        // =================================================================
        // STEP 2: De-duplication on the normalized list
        // =================================================================
        List<MultivalueSorItemHandlingActionInput> finalOutput = new ArrayList<>();
        Set<String> uniqueKeys = new HashSet<>();

        for (MultivalueSorItemHandlingActionInput item : normalizedList) {
            // Skip items already marked as removed during normalization (the original multi-value container)
            if (item.isRemovedAfterFiltering()) {
                continue;
            }

            // Key based on the extracted data: Document + ItemName + Answer + Score (to detect exact duplicates)
            String key = String.format("%s|%s|%s", item.getOriginId(), item.getSorItemName(), item.getAnswer());

            if (uniqueKeys.add(key)) {
                // This is the first occurrence of this item/value combination (whether original or split).
                item.setRemovedAfterFiltering(false);
                item.setMessage(item.getMessage() != null ? item.getMessage().startsWith("Normalized") ? item.getMessage() + " Retained as unique." : "Retained as a unique multi_value item.": "Retained as a unique multi_value item.");
                finalOutput.add(item);
            } else {
                // Duplicate found.
                item.setRemovedAfterFiltering(true);
                item.setMessage("Removed as a duplicate multi_value item (same value/score found in another page/instance).");
            }
        }

        // Step 3: Add back the original items that were split, but mark them as removed (for auditing)
        multiValueInputs.stream().filter(MultivalueSorItemHandlingActionInput::isRemovedAfterFiltering).forEach(finalOutput::add);


        log.info(aMarker, "CASE 1: Retained {} unique multi_value records after normalization and de-duplication.", finalOutput.stream().filter(item -> !item.isRemovedAfterFiltering()).count());

        // Return all items (retained and removed originals) to preserve the full audit trail.
        return finalOutput;
    }

    /**
     * Creates a deep clone of the MultivalueSorItemHandlingActionInput object.
     * This is crucial for splitting multi-value answers without corrupting the original
     * or its audit trail.
     *
     * @param original The original item to be cloned.
     * @return A new MultivalueSorItemHandlingActionInput instance with all fields copied.
     */
    private MultivalueSorItemHandlingActionInput cloneInputItem(MultivalueSorItemHandlingActionInput original) {
        MultivalueSorItemHandlingActionInput clone = new MultivalueSorItemHandlingActionInput();

        // --- Core Data Fields ---
        clone.setStatus(original.getStatus());
        clone.setAnswer(original.getAnswer());
        clone.setBBox(original.getBBox());
        clone.setDocumentId(original.getDocumentId());
        clone.setGroupId(original.getGroupId());
        clone.setModelId(original.getModelId());
        clone.setModelInfo(original.getModelInfo());
        clone.setOriginId(original.getOriginId());
        clone.setPaperNo(original.getPaperNo());
        clone.setQuestionId(original.getQuestionId());
        clone.setRootPipelineId(original.getRootPipelineId());
        clone.setScore(original.getScore());
        clone.setSorItemAttributionId(original.getSorItemAttributionId());
        clone.setSorItemName(original.getSorItemName());
        clone.setSorQuestion(original.getSorQuestion());
        clone.setSynonymId(original.getSynonymId());
        clone.setTenantId(original.getTenantId());
        clone.setVqaScore(original.getVqaScore());
        clone.setModelRegistry(original.getModelRegistry());
        clone.setCategory(original.getCategory());
        clone.setStage(original.getStage());
        clone.setBatchId(original.getBatchId());
        clone.setLineItemType(original.getLineItemType());
        clone.setIsEncrypted(original.getIsEncrypted());
        clone.setEncryptionPolicyId(original.getEncryptionPolicyId());
        clone.setEncryptionPolicy(original.getEncryptionPolicy());
        clone.setSorContainerInstance(original.getSorContainerInstance());
        clone.setIsMultiEntityEnabled(original.getIsMultiEntityEnabled());
        clone.setSorContainerName(original.getSorContainerName());
        clone.setSectionAlias(original.getSectionAlias());
        clone.setWhitelistedSections(original.getWhitelistedSections());

        // --- Audit Fields (IMPORTANT: These will be reset/updated after cloning) ---
        // Copy them over, but the calling method will reset isRemovedAfterFiltering and Message.
        clone.setRemovedAfterFiltering(original.isRemovedAfterFiltering());
        clone.setMessage(original.getMessage());
        clone.setSectionPriorityAfterFilter(original.getSectionPriorityAfterFilter());

        return clone;
    }


    private List<MultivalueSorItemHandlingActionInput> handleCase3MultiEntityEnabled(List<MultivalueSorItemHandlingActionInput> inputs, Marker aMarker, Logger log, ActionExecutionAudit action) throws HandymanException {

        log.info(aMarker, "CASE 3: Processing {} multi-entity enabled single_value records.", inputs.size());

        // Group 1: Group by OriginId -> SorContainerInstance -> SorItemName
        Map<String, List<MultivalueSorItemHandlingActionInput>> groupedByOrigin = inputs.stream().collect(Collectors.groupingBy(MultivalueSorItemHandlingActionInput::getOriginId));

        List<MultivalueSorItemHandlingActionInput> output = new ArrayList<>();

        for (List<MultivalueSorItemHandlingActionInput> originInputs : groupedByOrigin.values()) {

            // Group 2: Group by SorItemName (to find competing answers for the same field)
            Map<String, List<MultivalueSorItemHandlingActionInput>> competingItemsMap = originInputs.stream().collect(Collectors.groupingBy(MultivalueSorItemHandlingActionInput::getSorItemName));

            for (List<MultivalueSorItemHandlingActionInput> competingInputs : competingItemsMap.values()) {

                // --- Sub-Step 1: Apply Whitelist Priority Filter (Across all instances) ---
                MultivalueSorItemHandlingActionInput retainedItem = applyWhitelistPriorityFilter(competingInputs, aMarker, log, action);

                if (retainedItem != null) {
                    // --- Sub-Step 2: Group by sorContainerInstance and keep highest score if no priority match ---
                    // The requirement: "If no priority matches then need to group the data by sorContainerInstance and
                    // return the value having highest sorItemData for each page one page should contains only one sorContainerinstance"

                    // Since `applyWhitelistPriorityFilter` already returned the highest priority item,
                    // we now need to ensure only ONE instance is kept PER PAGE/CONTAINER GROUPING.

                    // However, for multi-entity enabled, we usually keep all distinct instances.
                    // The most logical interpretation is that the whitelist determines the canonical value,
                    // and the grouping by instance is the final output structure.

                    // We rely on the initial whitelist filter to select the best record for that SorItemName.
                    output.add(retainedItem);
                }
            }
        }

        log.info(aMarker, "CASE 3: Retained {} multi-entity enabled records after priority filtering.", output.size());
        return output;
    }

    /**
     * CASE 4: Process 'single_value' items where isMultiEntityEnabled is FALSE.
     * This involves priority filtering AND consolidation across pages/instances based on grouping keys.
     */
    private List<MultivalueSorItemHandlingActionInput> handleCase4MultiEntityDisabled(List<MultivalueSorItemHandlingActionInput> inputs, Marker aMarker, Logger log, ActionExecutionAudit action) throws HandymanException {

        log.info(aMarker, "CASE 4: Processing {} multi-entity disabled single_value records.", inputs.size());

        // --- Sub-Step 1: Apply Whitelist Priority Filtering (to select the best answer for each SorItemName) ---
        List<MultivalueSorItemHandlingActionInput> prioritizedInputs = new ArrayList<>();

        Map<String, List<MultivalueSorItemHandlingActionInput>> groupedByItemName = inputs.stream().collect(Collectors.groupingBy(MultivalueSorItemHandlingActionInput::getSorItemName));

        for (List<MultivalueSorItemHandlingActionInput> competingInputs : groupedByItemName.values()) {
            MultivalueSorItemHandlingActionInput retainedItem = applyWhitelistPriorityFilter(competingInputs, aMarker, log, action);
            if (retainedItem != null) {
                prioritizedInputs.add(retainedItem);
            }
        }

        log.info(aMarker, "CASE 4: Retained {} records after initial whitelist priority filtering.", prioritizedInputs.size());

        // --- Sub-Step 2: Consolidation Logic (Grouping across pages/instances) ---
        return consolidateMultiPageData(prioritizedInputs, aMarker, log);
    }

    /**
     * Handles the consolidation of single-entity data across multiple pages/instances.
     * Logic: Group by MEMBER_GROUPING_KEYS (memberId, memberName, memberDob) to create a single canonical set of data.
     */
    private List<MultivalueSorItemHandlingActionInput> consolidateMultiPageData(List<MultivalueSorItemHandlingActionInput> prioritizedInputs, Marker aMarker, Logger log) {

        // Grouping by (OriginId + SorContainerName) is assumed to define the logical Container
        Map<String, List<MultivalueSorItemHandlingActionInput>> groupedByContainer = prioritizedInputs.stream().collect(Collectors.groupingBy(input -> input.getOriginId() + "_" + input.getSorContainerName()));

        List<MultivalueSorItemHandlingActionInput> consolidatedOutput = new ArrayList<>();

        for (Map.Entry<String, List<MultivalueSorItemHandlingActionInput>> containerEntry : groupedByContainer.entrySet()) {
            List<MultivalueSorItemHandlingActionInput> itemsInContainer = containerEntry.getValue();

            // Sub-group by the grouping keys (memberId, memberName, memberDob)
            Map<String, List<MultivalueSorItemHandlingActionInput>> mergedRecords = new HashMap<>();

            for (MultivalueSorItemHandlingActionInput item : itemsInContainer) {
                String groupingKey = generateGroupingKey(item, itemsInContainer);
                mergedRecords.computeIfAbsent(groupingKey, k -> new ArrayList<>()).add(item);
            }

            // Process Merged Records (Conflict Resolution: keep the highest score for non-key items)
            for (List<MultivalueSorItemHandlingActionInput> itemsToMerge : mergedRecords.values()) {

                // Further group by SorItemName (since different pages can provide answers for the same SorItemName)
                Map<String, MultivalueSorItemHandlingActionInput> finalCanonicalItems = new HashMap<>();

                for (MultivalueSorItemHandlingActionInput item : itemsToMerge) {
                    String itemName = item.getSorItemName();

                    if (!finalCanonicalItems.containsKey(itemName) || item.getScore() > finalCanonicalItems.get(itemName).getScore()) {

                        // Keep this item if it's new OR if it has a higher score (conflict resolution)
                        if (finalCanonicalItems.containsKey(itemName)) {
                            finalCanonicalItems.get(itemName).setRemovedAfterFiltering(true);
                            finalCanonicalItems.get(itemName).setMessage("Removed by consolidation/score conflict: Retained item score " + item.getScore());
                        }

                        item.setRemovedAfterFiltering(false);
                        item.setMessage("Retained by consolidation (or highest score conflict resolution).");
                        finalCanonicalItems.put(itemName, item);
                    } else {
                        item.setRemovedAfterFiltering(true);
                        item.setMessage("Removed by consolidation/score conflict: Retained item score " + finalCanonicalItems.get(itemName).getScore());
                    }
                }
                consolidatedOutput.addAll(finalCanonicalItems.values());
            }
        }
        log.info(aMarker, "CASE 4: Retained {} records after multi-page consolidation.", consolidatedOutput.size());
        return consolidatedOutput;
    }

    // Helper: Generates a key using the available member grouping keys (Id, Name, DOB)
    private String generateGroupingKey(MultivalueSorItemHandlingActionInput currentItem, List<MultivalueSorItemHandlingActionInput> allItemsInContainer) {

        // Find any key items associated with this container to group
        String key = allItemsInContainer.stream().filter(item -> MEMBER_GROUPING_KEYS.contains(item.getSorItemName())).map(item -> item.getSorItemName() + ":" + item.getAnswer()).collect(Collectors.joining("|"));

        // If no grouping keys are present across any page in the container,
        // the items are assumed to belong to a single "default" group.
        if (key.isEmpty()) {
            return "NO_MEMBER_KEY_FOUND";
        }
        return key;
    }

    /**
     * Applies the filtering based on whitelistedSections and priorityLevel.
     * If multiple answers exist for the same SorItemName, only the one from the highest priority sectionAlias is kept.
     */
    private MultivalueSorItemHandlingActionInput applyWhitelistPriorityFilter(List<MultivalueSorItemHandlingActionInput> competingInputs, Marker aMarker, Logger log, ActionExecutionAudit action) throws HandymanException {

        if (competingInputs.size() <= 1) {
            if (!competingInputs.isEmpty()) {
                competingInputs.get(0).setRemovedAfterFiltering(false);
                competingInputs.get(0).setMessage("Retained as only one candidate found.");
            }
            return competingInputs.isEmpty() ? null : competingInputs.get(0);
        }

        try {
            // Assume all competing inputs share the same whitelistedSections configuration
            String whitelistedSectionsJson = competingInputs.get(0).getWhitelistedSections();
            if (whitelistedSectionsJson == null || whitelistedSectionsJson.isEmpty()) {
                // Fallback: No whitelist, take the one with the highest score
                MultivalueSorItemHandlingActionInput maxScoreItem = competingInputs.stream().max(Comparator.comparingDouble(MultivalueSorItemHandlingActionInput::getScore)).orElse(null);

                if (maxScoreItem != null) {
                    competingInputs.stream().filter(item -> item != maxScoreItem).forEach(item -> {
                        item.setRemovedAfterFiltering(true);
                        item.setMessage("Removed by max score fallback (No whitelist config).");
                    });
                    maxScoreItem.setRemovedAfterFiltering(false);
                    maxScoreItem.setMessage("Retained by max score fallback (No whitelist config).");
                }
                return maxScoreItem;
            }

            // 1. Parse Whitelist and sort by priority (1 is highest)
            List<WhitelistEntry> whitelist = objectMapper.readValue(whitelistedSectionsJson, new TypeReference<List<WhitelistEntry>>() {
            });
            whitelist.sort(Comparator.comparingInt(WhitelistEntry::getPriorityLevel));

            // 2. Find the best match
            MultivalueSorItemHandlingActionInput bestMatch = null;
            for (WhitelistEntry whiteEntry : whitelist) {
                String targetAlias = whiteEntry.getTruthEntity();

                Optional<MultivalueSorItemHandlingActionInput> match = competingInputs.stream().filter(item -> targetAlias.equalsIgnoreCase(item.getSectionAlias())).findFirst();

                if (match.isPresent()) {
                    bestMatch = match.get();
                    bestMatch.setSectionPriorityAfterFilter(String.valueOf(whiteEntry.getPriorityLevel()));
                    break; // Found the highest priority match
                }
            }

            // 3. Final Selection and Messaging
            if (bestMatch != null) {
                bestMatch.setRemovedAfterFiltering(false);
                bestMatch.setMessage("Retained by Section Alias Priority: " + bestMatch.getSectionAlias());

                MultivalueSorItemHandlingActionInput finalBestMatch = bestMatch;
                MultivalueSorItemHandlingActionInput finalBestMatch1 = bestMatch;
                competingInputs.stream().filter(item -> item != finalBestMatch).forEach(item -> {
                    item.setRemovedAfterFiltering(true);
                    item.setMessage("Removed by lower Section Alias Priority. Retained alias: " + finalBestMatch1.getSectionAlias());
                });
                return bestMatch;
            } else {
                // Fallback: No item matches the whitelist. Use Max Score.
                MultivalueSorItemHandlingActionInput maxScoreItem = competingInputs.stream().max(Comparator.comparingDouble(MultivalueSorItemHandlingActionInput::getScore)).get(); // Safe because size > 1

                maxScoreItem.setRemovedAfterFiltering(false);
                maxScoreItem.setMessage("Retained by max score fallback (Alias did not match whitelist).");

                competingInputs.stream().filter(item -> item != maxScoreItem).forEach(item -> {
                    item.setRemovedAfterFiltering(true);
                    item.setMessage("Removed by max score fallback (Alias did not match whitelist). Retained score: " + maxScoreItem.getScore());
                });
                return maxScoreItem;
            }

        } catch (IOException e) {
            log.error(aMarker, "Error parsing whitelistedSections JSON for SorItemName: {}", competingInputs.get(0).getSorItemName());
            HandymanException handymanException = new HandymanException(e);
            HandymanException.insertException("Error in applyWhitelistPriorityFilter", handymanException, action);
            // Fallback: If parsing fails, revert to max score
            return competingInputs.stream().max(Comparator.comparingDouble(MultivalueSorItemHandlingActionInput::getScore)).orElse(null);

        }
    }

    public static List<MultivalueSorItemHandlingActionInput> selectMaxCountNodes(List<MultivalueSorItemHandlingActionInput> list) {

        if (list == null || list.isEmpty()) return Collections.emptyList();

        // Final output
        List<MultivalueSorItemHandlingActionInput> output = new ArrayList<>();

        // Step-1: Group by originId
        Map<String, List<MultivalueSorItemHandlingActionInput>> byOrigin = list.stream().collect(Collectors.groupingBy(MultivalueSorItemHandlingActionInput::getOriginId));

        for (Map.Entry<String, List<MultivalueSorItemHandlingActionInput>> originEntry : byOrigin.entrySet()) {

            // Step-2: Group by sorContainerName inside same originId
            Map<String, List<MultivalueSorItemHandlingActionInput>> byContainerName = originEntry.getValue().stream().collect(Collectors.groupingBy(MultivalueSorItemHandlingActionInput::getSorContainerName));

            for (Map.Entry<String, List<MultivalueSorItemHandlingActionInput>> containerEntry : byContainerName.entrySet()) {

                // Step-3: Group by (pageNo + sorContainerInstance)
                Map<String, List<MultivalueSorItemHandlingActionInput>> byPageAndInstance = containerEntry.getValue().stream().collect(Collectors.groupingBy(item -> item.getPaperNo() + "_" + item.getSorContainerInstance()));

                // Step-4: Evaluate groups to find max-count (with tie-break)
                Optional<Map.Entry<String, List<MultivalueSorItemHandlingActionInput>>> bestGroup = byPageAndInstance.entrySet().stream().sorted((e1, e2) -> {
                    // Compare by size DESC
                    int cmp = Integer.compare(e2.getValue().size(), e1.getValue().size());
                    if (cmp != 0) return cmp;

                    // tie → choose smaller pageNo
                    Long p1 = e1.getValue().get(0).getPaperNo();
                    Long p2 = e2.getValue().get(0).getPaperNo();
                    cmp = Long.compare(p1, p2);
                    if (cmp != 0) return cmp;

                    // final tie → keep any
                    return 0;
                }).findFirst();

                bestGroup.ifPresent(g -> output.addAll(g.getValue()));
            }
        }

        return output;
    }


    private static List<WhitelistEntry> parseWhitelistEntries(String json) {
        try {
            return objectMapper.readValue(json, new TypeReference<List<WhitelistEntry>>() {
            });
        } catch (Exception e) {
            return Collections.emptyList();
        }
    }


    @Override
    public boolean executeIf() throws Exception {
        return multivalueSorItemHandling.getCondition();
    }

    public List<MultivalueSorItemHandlingActionInput> fetchValuesFromDB(Jdbi jdbi) {
        final List<MultivalueSorItemHandlingActionInput> multivalueConcatenationInputs = new ArrayList<>();
        jdbi.useTransaction(handle -> {
            final List<String> formattedQuery = CommonQueryUtil.getFormattedQuery(multivalueSorItemHandling.getQuerySet());
            AtomicInteger i = new AtomicInteger(0);
            for (String sqlToExecute : formattedQuery) {
                log.info(aMarker, "executing  query {} from index {}", sqlToExecute, i.getAndIncrement());
                Query query = handle.createQuery(sqlToExecute);
                ResultIterable<MultivalueSorItemHandlingActionInput> resultIterable = query.mapToBean(MultivalueSorItemHandlingActionInput.class);
                List<MultivalueSorItemHandlingActionInput> processingExecutorInputs = resultIterable.stream().collect(Collectors.toList());
                multivalueConcatenationInputs.addAll(processingExecutorInputs);
                log.info(aMarker, "executed query from index {}", i.get());
            }
        });
        return multivalueConcatenationInputs;
    }

    public static List<MultivalueSorItemHandlingActionInput>
    updateSorItemNamesByContainerInstance(
            List<MultivalueSorItemHandlingActionInput> inputs
    ) {

        // 1️⃣ Group by (originId, paperNo)
        Map<GroupKey, List<MultivalueSorItemHandlingActionInput>> byDocument =
                inputs.stream()
                        .collect(Collectors.groupingBy(
                                i -> new GroupKey(i.getOriginId(), i.getPaperNo())
                        ));

        // 2️⃣ Process each document group
        byDocument.values().forEach(documentGroup -> {

            // Group by sorContainerInstance
            Map<String, List<MultivalueSorItemHandlingActionInput>> byContainer =
                    documentGroup.stream()
                            .collect(Collectors.groupingBy(
                                    MultivalueSorItemHandlingActionInput::getSorContainerInstance
                            ));

            // Sort container instances
            List<String> orderedContainers = byContainer.keySet().stream()
                    .sorted(Comparator.nullsLast(String::compareTo))
                    .collect(Collectors.toList());

            // Assign suffix per container instance
            int suffix = 1;
            for (String containerInstance : orderedContainers) {

                List<MultivalueSorItemHandlingActionInput> items =
                        byContainer.get(containerInstance);

                for (MultivalueSorItemHandlingActionInput item : items) {
                    item.setSorItemName(
                            item.getSorItemName() + "_" + suffix
                    );
                }
                suffix++;
            }
        });

        // 3️⃣ Same list, updated objects
        return inputs;
    }


    static final class GroupKey {
        private final String originId;
        private final Long paperNo;

        GroupKey(String originId, Long paperNo) {
            this.originId = originId;
            this.paperNo = paperNo;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof GroupKey)) return false;
            GroupKey that = (GroupKey) o;
            return Objects.equals(originId, that.originId)
                    && Objects.equals(paperNo, that.paperNo);
        }

        @Override
        public int hashCode() {
            return Objects.hash(originId, paperNo);
        }
    }


    public static class WhitelistEntry {
        private String truthEntity;
        private int priorityLevel;

        public String getTruthEntity() {
            return truthEntity;
        }

        public int getPriorityLevel() {
            return priorityLevel;
        }
    }

    public void decryptAnswers(List<MultivalueSorItemHandlingActionInput> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream()
                // Using `isEncrypted` property from the input object to determine if decryption is needed
                .filter(obj -> "true".equalsIgnoreCase(obj.getIsEncrypted())).filter(obj -> obj.getSorItemAttributionId() != null && obj.getAnswer() != null && !obj.getAnswer().isEmpty()).map(obj -> new EncryptionRequestClass(AES_256, obj.getAnswer(), String.valueOf(obj.getSorItemAttributionId()))).collect(Collectors.toList());
        log.info(aMarker, "Total records to decrypt for answers (Input): {}", encryptionRequests.size());

        if (encryptionRequests.isEmpty()) return;

        try {
            // Step 2: Call external Protegrity API
            List<EncryptionRequestClass> responseList = encryption.decrypt(encryptionRequests);

            // Step 3: Build a lookup map from response (Key: SorItemAttributionId)
            Map<Long, String> decryptedMap = responseList.stream().filter(item -> item.getKey() != null && item.getKey().matches("\\d+")).collect(Collectors.toMap(item -> Long.parseLong(item.getKey()), EncryptionRequestClass::getValue));

            // Step 4: Update original list
            for (MultivalueSorItemHandlingActionInput item : inputList) {
                if (item.getSorItemAttributionId() != null && decryptedMap.containsKey(item.getSorItemAttributionId())) {
                    item.setAnswer(decryptedMap.get(item.getSorItemAttributionId()));
                }
            }
        } catch (Exception e) {
            log.error(aMarker, "Decryption failed for Answers on input data.", e);
            // Depending on requirements, you might throw or handle gracefully.
        }
    }

    public void decryptSectionAlias(List<MultivalueSorItemHandlingActionInput> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream().filter(obj -> obj.getSorItemAttributionId() != null && obj.getSectionAlias() != null && !obj.getSectionAlias().isEmpty()).map(obj -> new EncryptionRequestClass(AES_256, obj.getSectionAlias(), String.valueOf(obj.getSorItemAttributionId()))).collect(Collectors.toList());
        log.info(aMarker, "Total records to decrypt for section alias (Input): {}", encryptionRequests.size());

        if (encryptionRequests.isEmpty()) return;

        try {
            List<EncryptionRequestClass> responseList = encryption.decrypt(encryptionRequests);

            // Step 3: Build a lookup map from response (Key: SorItemAttributionId)
            Map<Long, String> decryptedMap = responseList.stream().filter(item -> item.getKey() != null && item.getKey().matches("\\d+")).collect(Collectors.toMap(item -> Long.parseLong(item.getKey()), EncryptionRequestClass::getValue));

            // Step 4: Update original list
            for (MultivalueSorItemHandlingActionInput item : inputList) {
                if (item.getSorItemAttributionId() != null && decryptedMap.containsKey(item.getSorItemAttributionId())) {
                    item.setSectionAlias(decryptedMap.get(item.getSorItemAttributionId()));
                }
            }
        } catch (Exception e) {
            log.error(aMarker, "Decryption failed for Section Alias on input data.", e);
        }
    }

    public void decryptLabels(List<MultivalueSorItemHandlingActionInput> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream().filter(obj -> obj.getSorItemAttributionId() != null && obj.getSorQuestion() != null && !obj.getSorQuestion().isEmpty()) // Assuming SorQuestion is the label field
                .map(obj -> new EncryptionRequestClass(AES_256, obj.getSorQuestion(), String.valueOf(obj.getSorItemAttributionId()))).collect(Collectors.toList());
        log.info(aMarker, "Total records to decrypt for labels (Input): {}", encryptionRequests.size());

        if (encryptionRequests.isEmpty()) return;

        try {
            List<EncryptionRequestClass> responseList = encryption.decrypt(encryptionRequests);

            // Step 3: Build a lookup map from response (Key: SorItemAttributionId)
            Map<Long, String> decryptedMap = responseList.stream().filter(item -> item.getKey() != null && item.getKey().matches("\\d+")).collect(Collectors.toMap(item -> Long.parseLong(item.getKey()), EncryptionRequestClass::getValue));

            // Step 4: Update original list
            for (MultivalueSorItemHandlingActionInput item : inputList) {
                if (item.getSorItemAttributionId() != null && decryptedMap.containsKey(item.getSorItemAttributionId())) {
                    item.setSorQuestion(decryptedMap.get(item.getSorItemAttributionId()));
                }
            }
        } catch (Exception e) {
            log.error(aMarker, "Decryption failed for Labels (SorQuestion) on input data.", e);
        }
    }

    public void encryptAnswers(List<MultiValueOutputResult> outputList, InticsIntegrity encryption) {
        if (outputList == null || outputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = outputList.stream()
                // Using `isEncrypted` property from the output object
                .filter(obj -> "true".equalsIgnoreCase(String.valueOf(obj.getIsEncrypted()))).filter(obj -> obj.getId() != null && obj.getAnswer() != null && !obj.getAnswer().isEmpty()).map(obj -> new EncryptionRequestClass(AES_256, obj.getAnswer(), String.valueOf(obj.getId()))).collect(Collectors.toList());
        log.info(aMarker, "Total records to encrypt for answers (Output): {}", encryptionRequests.size());

        if (encryptionRequests.isEmpty()) return;

        try {
            // Step 2: Call external Protegrity API
            List<EncryptionRequestClass> responseList = encryption.encrypt(encryptionRequests);

            // Step 3: Build a lookup map from response (Key: SorItemAttributionId)
            Map<String, String> encryptedMap = responseList.stream().filter(item -> item.getKey() != null && item.getKey().matches("\\d+")).collect(Collectors.toMap(EncryptionRequestClass::getKey, EncryptionRequestClass::getValue));

            // Step 4: Update original list
            for (MultiValueOutputResult item : outputList) {
                if (item.getId() != null && encryptedMap.containsKey(item.getId())) {
                    item.setAnswer(encryptedMap.get(item.getId()));
                }
            }
        } catch (Exception e) {
            log.error(aMarker, "Encryption failed for Answers on output data. Proceeding unencrypted.", e);
        }
    }


    public void encryptLabels(List<MultiValueOutputResult> outputList, InticsIntegrity encryption) {
        if (outputList == null || outputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = outputList.stream().filter(obj -> obj.getId() != null && obj.getSorQuestion() != null && !obj.getSorQuestion().isEmpty()) // Assuming SorQuestion is the label field
                .map(obj -> new EncryptionRequestClass(AES_256, obj.getSorQuestion(), String.valueOf(obj.getId()))).collect(Collectors.toList());
        log.info(aMarker, "Total records to encrypt for labels (Output): {}", encryptionRequests.size());

        if (encryptionRequests.isEmpty()) return;

        try {
            List<EncryptionRequestClass> responseList = encryption.encrypt(encryptionRequests);

            // Step 3: Build a lookup map from response (Key: SorItemAttributionId)
            Map<String, String> encryptedMap = responseList.stream().filter(item -> item.getKey() != null && item.getKey().matches("\\d+")).collect(Collectors.toMap(EncryptionRequestClass::getKey, EncryptionRequestClass::getValue));

            // Step 4: Update original list
            for (MultiValueOutputResult item : outputList) {
                if (item.getId() != null && encryptedMap.containsKey(item.getId())) {
                    item.setSorQuestion(encryptedMap.get(item.getId()));
                }
            }
        } catch (Exception e) {
            log.error(aMarker, "Encryption failed for Labels (SorQuestion) on output data. Proceeding unencrypted.", e);
        }
    }

}
