package in.handyman.raven.lib;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import in.handyman.raven.core.encryption.SecurityEngine;
import in.handyman.raven.core.encryption.inticsgrity.InticsIntegrity;
import in.handyman.raven.exception.HandymanException;
import in.handyman.raven.lambda.access.ResourceAccess;
import in.handyman.raven.lambda.action.ActionExecution;
import in.handyman.raven.lambda.action.IActionExecution;
import in.handyman.raven.lambda.doa.audit.ActionExecutionAudit;
import in.handyman.raven.lib.contracts.IMultivalueSorItemHandling;
import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Function;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import in.handyman.raven.lib.model.MultivalueSorItemHandling;
import in.handyman.raven.lib.model.soritemhandling.MultiValueOutputResult;
import in.handyman.raven.lib.model.soritemhandling.MultivalueSorItemHandlingActionInput;
import in.handyman.raven.util.CommonQueryUtil;

import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.core.result.ResultIterable;
import org.jdbi.v3.core.statement.Query;
import org.jetbrains.annotations.NotNull;
import org.slf4j.Logger;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

import static in.handyman.raven.core.enums.EncryptionConstants.ENCRYPT_ITEM_WISE_ENCRYPTION;

/**
 * Auto Generated By Raven
 */
@ActionExecution(
    actionName = "MultivalueSorItemHandling"
)
public class MultivalueSorItemHandlingAction implements IMultivalueSorItemHandling, IActionExecution {
  private final ActionExecutionAudit action;

  private final Logger log;

  private final MultivalueSorItemHandling multivalueSorItemHandling;
    static ObjectMapper mapper = new ObjectMapper();

  private final Marker aMarker;
  public static final String AES_256 = "AES256";
    private static final Pattern TRAILING_NUMBER = Pattern.compile("_(\\d+)$");

    public MultivalueSorItemHandlingAction(final ActionExecutionAudit action, final Logger log,
      final Object multivalueSorItemHandling) {
    this.multivalueSorItemHandling = (MultivalueSorItemHandling) multivalueSorItemHandling;
    this.action = action;
    this.log = log;
    this.aMarker = MarkerFactory.getMarker(" MultivalueSorItemHandling:"+this.multivalueSorItemHandling.getName());
  }

  @Override
  public void execute() throws Exception {
      try{
          final Jdbi jdbi = ResourceAccess.rdbmsJDBIConn(multivalueSorItemHandling.getResourceConn());
          InticsIntegrity encryption = SecurityEngine.getInticsIntegrityMethod(action,log);
          String pipelineEndToEndEncryptionActivatorStr = action.getContext().get(ENCRYPT_ITEM_WISE_ENCRYPTION);
          boolean pipelineEndToEndEncryptionActivator = Boolean.parseBoolean(pipelineEndToEndEncryptionActivatorStr);

          String outputTableName = multivalueSorItemHandling.getOutputTable();
          final List<MultivalueSorItemHandlingActionInput> multivalueConcatenationInputs = fetchValuesFromDB(jdbi);
          final List<MultiValueOutputResult> output = new ArrayList<>();

//          remapSorContainerInstances(multivalueConcatenationInputs);


          List<MultivalueSorItemHandlingActionInput> singleValueFilteredList =
                  multivalueConcatenationInputs.stream()
                          .filter(item -> "single_value".equals(item.getLineItemType()) && !"multiple_member_indicator".equals(item.getSorItemName()))
                          .collect(Collectors.toList());

          List<MultivalueSorItemHandlingActionInput> multiValueFilteredList =
                  multivalueConcatenationInputs.stream()
                          .filter(item -> "multi_value".equals(item.getLineItemType()) && !"multiple_member_indicator".equals(item.getSorItemName()))
                          .collect(Collectors.toList());

          List<MultivalueSorItemHandlingActionInput> multiMemberKeyFilteredList =
                  multivalueConcatenationInputs.stream()
                          .filter(item -> "multiple_member_indicator".equals(item.getSorItemName()))
                          .collect(Collectors.toList());

          List<MultivalueSorItemHandlingActionInput> maxSingleValueFilteredList=filterBySectionAliasOrFallback(singleValueFilteredList);

          handleSingleValueLineItems(maxSingleValueFilteredList, pipelineEndToEndEncryptionActivator, encryption, output);

          handleMultiValueLineItems(multiValueFilteredList, pipelineEndToEndEncryptionActivator, encryption, output);

          handleSingleValueLineItems(multiMemberKeyFilteredList, pipelineEndToEndEncryptionActivator, encryption, output);

          outputBuilderAndInsert(jdbi, outputTableName, output);

          log.info(aMarker, "Successfully inserted {} records into {}", output.size(), outputTableName);



      } catch (Exception e){
          log.error(aMarker, "Error in execute method for Multi value concatenation ", e);
          HandymanException handymanException = new HandymanException(e);
          HandymanException.insertException("Multi value concatenation failed ", handymanException, action);
      }


  }

    public List<MultivalueSorItemHandlingActionInput> filterBySectionAliasOrFallback(
            List<MultivalueSorItemHandlingActionInput> inputs
    ) {
        if (inputs == null || inputs.isEmpty()) {
            return Collections.emptyList();
        }

        ObjectMapper mapper = new ObjectMapper();
        List<MultivalueSorItemHandlingActionInput> finalOutput = new ArrayList<>();

        // -------------------------------
        // Group base: originId → paperNo → sorContainerInstance
        // -------------------------------
        Map<String, Map<Long, Map<String, List<MultivalueSorItemHandlingActionInput>>>> grouped =
                inputs.stream().collect(
                        Collectors.groupingBy(
                                MultivalueSorItemHandlingActionInput::getOriginId,
                                Collectors.groupingBy(
                                        MultivalueSorItemHandlingActionInput::getPaperNo,
                                        Collectors.groupingBy(
                                                MultivalueSorItemHandlingActionInput::getSorContainerInstance
                                        )
                                )
                        )
                );

        // Process each instance group
        for (String originId : grouped.keySet()) {
            for (Long paperNo : grouped.get(originId).keySet()) {
                for (String instance : grouped.get(originId).get(paperNo).keySet()) {

                    List<MultivalueSorItemHandlingActionInput> instanceList =
                            grouped.get(originId).get(paperNo).get(instance);

                    // For priority selection
                    int bestPriority = Integer.MAX_VALUE;
                    List<MultivalueSorItemHandlingActionInput> bestMatches = new ArrayList<>();

                    for (MultivalueSorItemHandlingActionInput item : instanceList) {

                        String rawJson = item.getWhitelistedSections();
                        String alias = item.getSectionAlias();

                        if (rawJson == null || alias == null) {
                            continue;
                        }

                        try {
                            List<Map<String, Object>> parsed =
                                    mapper.readValue(rawJson, new TypeReference<List<Map<String, Object>>>() {});

                            for (Map<String, Object> entry : parsed) {
                                String truthEntity = (String) entry.get("truthEntity");
                                Integer priority = (Integer) entry.get("priorityLevel");

                                if (truthEntity == null || priority == null) continue;

                                // contains-match (case insensitive)
                                if (alias.toLowerCase().contains(truthEntity.toLowerCase())) {

                                    if (priority < bestPriority) { // smaller = higher priority
                                        bestPriority = priority;
                                        bestMatches.clear();
                                        bestMatches.add(item);
                                    } else if (priority == bestPriority) {
                                        bestMatches.add(item);
                                    }
                                }
                            }

                        } catch (Exception e) {
                            // ignore JSON parse errors for this entry
                        }
                    }

                    // If at least one priority-based match exists
                    if (!bestMatches.isEmpty()) {
                        finalOutput.addAll(bestMatches);
                    }
                }
            }
        }

        // -------------------------------
        // If priority-based filtering returned something → apply max-group logic
        // -------------------------------
        if (!finalOutput.isEmpty()) {
            return selectMaxCountNodes(finalOutput);
        }

        // -------------------------------
        // Priority returned ZERO → fallback
        // -------------------------------
        return selectMaxCountNodes(inputs);
    }


    public static List<MultivalueSorItemHandlingActionInput> selectMaxCountNodes(
            List<MultivalueSorItemHandlingActionInput> list) {

        if (list == null || list.isEmpty()) return Collections.emptyList();

        // Final output
        List<MultivalueSorItemHandlingActionInput> output = new ArrayList<>();

        // Step-1: Group by originId
        Map<String, List<MultivalueSorItemHandlingActionInput>> byOrigin =
                list.stream().collect(Collectors.groupingBy(MultivalueSorItemHandlingActionInput::getOriginId));

        for (Map.Entry<String, List<MultivalueSorItemHandlingActionInput>> originEntry : byOrigin.entrySet()) {

            // Step-2: Group by sorContainerName inside same originId
            Map<String, List<MultivalueSorItemHandlingActionInput>> byContainerName =
                    originEntry.getValue().stream()
                            .collect(Collectors.groupingBy(MultivalueSorItemHandlingActionInput::getSorContainerName));

            for (Map.Entry<String, List<MultivalueSorItemHandlingActionInput>> containerEntry : byContainerName.entrySet()) {

                // Step-3: Group by (pageNo + sorContainerInstance)
                Map<String, List<MultivalueSorItemHandlingActionInput>> byPageAndInstance =
                        containerEntry.getValue().stream().collect(Collectors.groupingBy(item ->
                                item.getPaperNo() + "_" + item.getSorContainerInstance()
                        ));

                // Step-4: Evaluate groups to find max-count (with tie-break)
                Optional<Map.Entry<String, List<MultivalueSorItemHandlingActionInput>>> bestGroup =
                        byPageAndInstance.entrySet().stream()
                                .sorted((e1, e2) -> {
                                    // Compare by size DESC
                                    int cmp = Integer.compare(e2.getValue().size(), e1.getValue().size());
                                    if (cmp != 0) return cmp;

                                    // tie → choose smaller pageNo
                                    Long p1 = e1.getValue().get(0).getPaperNo();
                                    Long p2 = e2.getValue().get(0).getPaperNo();
                                    cmp = Long.compare(p1, p2);
                                    if (cmp != 0) return cmp;

                                    // final tie → keep any
                                    return 0;
                                })
                                .findFirst();

                bestGroup.ifPresent(g -> output.addAll(g.getValue()));
            }
        }

        return output;
    }


    private static List<WhitelistEntry> parseWhitelistEntries(String json) {
        try {
            return mapper.readValue(json, new TypeReference<List<WhitelistEntry>>() {});
        } catch (Exception e) {
            return Collections.emptyList();
        }
    }


    public List<MultiValueOutputResult> getSingleValueOutputResults(List<MultivalueSorItemHandlingActionInput> multivalueConcatenationInputs, boolean pipelineEndToEndEncryptionActivator, InticsIntegrity encryption, String outputTableName){
        return List.of();
    }
    @NotNull
    private List<MultiValueOutputResult> getMultiValueOutputResults(List<MultivalueSorItemHandlingActionInput> multivalueConcatenationInputs, boolean pipelineEndToEndEncryptionActivator, InticsIntegrity encryption, String outputTableName) {
        final List<MultiValueOutputResult> multivalueConcatenationOutput = handleValueSplitting(multivalueConcatenationInputs, pipelineEndToEndEncryptionActivator, encryption);
        Map<String, List<MultiValueOutputResult>> cleanedList = groupByOriginAndRemoveDuplicateAnswers(multivalueConcatenationOutput);
        List<MultiValueOutputResult> encryptedValue = encryptData(cleanedList, pipelineEndToEndEncryptionActivator, encryption);
        log.info(aMarker, "Successfully processed {} records for insertion into {}", encryptedValue.size(), outputTableName);
        return encryptedValue;
    }

    @Override
  public boolean executeIf() throws Exception {
    return multivalueSorItemHandling.getCondition();
  }

    public List<MultivalueSorItemHandlingActionInput> fetchValuesFromDB(Jdbi jdbi) {
        final List<MultivalueSorItemHandlingActionInput> multivalueConcatenationInputs = new ArrayList<>();
        jdbi.useTransaction(handle -> {
            final List<String> formattedQuery = CommonQueryUtil.getFormattedQuery(multivalueSorItemHandling.getQuerySet());
            AtomicInteger i = new AtomicInteger(0);
            for (String sqlToExecute : formattedQuery) {
                log.info(aMarker, "executing  query {} from index {}", sqlToExecute, i.getAndIncrement());
                Query query = handle.createQuery(sqlToExecute);
                ResultIterable<MultivalueSorItemHandlingActionInput> resultIterable = query.mapToBean(MultivalueSorItemHandlingActionInput.class);
                List<MultivalueSorItemHandlingActionInput> processingExecutorInputs = resultIterable.stream().collect(Collectors.toList());
                multivalueConcatenationInputs.addAll(processingExecutorInputs);
                log.info(aMarker, "executed query from index {}", i.get());
            }
        });
        return multivalueConcatenationInputs;
    }


    public List<MultiValueOutputResult> handleValueSplitting(List<MultivalueSorItemHandlingActionInput> multivalueSorItemHandlingActionInput, Boolean pipelineEndToEndEncryptionActivator, InticsIntegrity encryption) {

        final List<MultiValueOutputResult> output = new ArrayList<>();

        handleMultiValueLineItems(multivalueSorItemHandlingActionInput, pipelineEndToEndEncryptionActivator, encryption, output);

        handleSingleValueLineItems(multivalueSorItemHandlingActionInput, pipelineEndToEndEncryptionActivator, encryption, output);

        return output;
    }


    private void handleSingleValueLineItems(List<MultivalueSorItemHandlingActionInput> multivalueSorItemHandlingActionInput, Boolean pipelineEndToEndEncryptionActivator, InticsIntegrity encryption, List<MultiValueOutputResult> output) {

        multivalueSorItemHandlingActionInput.forEach(multivalueSorItemHandlingActionInput1 -> {
            output.add(buildOutputResult(multivalueSorItemHandlingActionInput1, multivalueSorItemHandlingActionInput1.getAnswer(), pipelineEndToEndEncryptionActivator, encryption));
            log.info(aMarker, "Filtered multi value item for document id {}", multivalueSorItemHandlingActionInput1.getDocumentId());
        });

    }

    private void handleMultiValueLineItems(List<MultivalueSorItemHandlingActionInput> multivalueSorItemHandlingActionInput, Boolean pipelineEndToEndEncryptionActivator, InticsIntegrity encryption, List<MultiValueOutputResult> output) {
        AtomicInteger counter = new AtomicInteger(1);

        for (MultivalueSorItemHandlingActionInput input : multivalueSorItemHandlingActionInput) {
            String sorItemValue = input.getAnswer();
            if (sorItemValue == null || sorItemValue.isBlank()) {
                log.info(aMarker, "Empty answer for document {}", input.getDocumentId());
                continue;
            }
            Integer increment = counter.incrementAndGet();
            String encryptionKey = input.getOriginId().concat("_").concat(input.getSorItemName());
            String finalEncryptionKey = encryptionKey.concat("_").concat(String.valueOf(increment));
            String decryptVal = input.getAnswer();

            if (decryptVal != null && decryptVal.contains(",")) {
                String[] splitValues = decryptVal.split("\\s*,\\s*");
                // decrypt
                for (String value : splitValues) {
                    // remove duplicates
                    output.add(buildOutputResult(input, value, pipelineEndToEndEncryptionActivator, encryption));
                }
            }else {
                output.add(buildOutputResult(input, input.getAnswer(), pipelineEndToEndEncryptionActivator, encryption));

            }

        }

    }

    @Override
    public List<MultiValueOutputResult> splitCommaSeparatedValues(List<MultivalueSorItemHandlingActionInput> multivalueSorItemHandlingActionInput, Boolean pipelineEndToEndEncryptionActivator, InticsIntegrity encryption) {
        return List.of();
    }

    public MultiValueOutputResult buildOutputResult(MultivalueSorItemHandlingActionInput input, String answer, Boolean pipelineEndToEndEncryptionActivator, InticsIntegrity encryption) {

            return MultiValueOutputResult.builder()
                .sorItemName(input.getSorItemName())
                .answer(answer)
                .bBox(input.getBBox())
                .groupId(input.getGroupId())
                .batchId(input.getBatchId())
                .category(input.getCategory())
                .documentId(input.getDocumentId())
                .lineItemType(input.getLineItemType())
                .modelId(input.getModelId())
                .modelInfo(input.getModelInfo())
                .modelRegistry(input.getModelRegistry())
                .originId(input.getOriginId())
                .paperNo(input.getPaperNo())
                .questionId(input.getQuestionId())
                .sorItemAttributionId(input.getSorItemAttributionId())
                .rootPipelineId(input.getRootPipelineId())
                .score(input.getScore())
                .sorQuestion(input.getSorQuestion())
                .stage(input.getStage())
                .status(input.getStatus())
                .synonymId(input.getSynonymId())
                .tenantId(input.getTenantId())
                .vqaScore(input.getVqaScore())
                .sorContainerInstance(input.getSorContainerInstance())
                .isMultiEntityEnabled(input.getIsMultiEntityEnabled())
                .build();
    }

    @Override
    public void outputBuilder(Jdbi jdbi, String outputTable, List<MultiValueOutputResult> outputs) {
        outputBuilderAndInsert(jdbi, outputTable, outputs);
    }

    public void outputBuilderAndInsert(Jdbi jdbi, String outputTable, List<MultiValueOutputResult> outputs) {
        if (outputs.isEmpty()) {
            log.info(aMarker, "No records to insert into {}", outputTable);
            return;
        }

        String sql = "INSERT INTO " + outputTable + " (" +
                "sor_item_name, answer, b_box, group_id, batch_id, category, document_id, line_item_type, " +
                "model_id, model_info, model_registry, origin_id, paper_no, question_id, sor_item_attribution_id, " +
                "root_pipeline_id, score, sor_question, stage, status, synonym_id, tenant_id, vqa_score, is_encrypted, encryption_policy_id, encryption_policy,sor_container_instance, created_on, last_updated_on" +
                ") VALUES (" +
                ":sorItemName, :answer, :BBox, :groupId, :batchId, :category, :documentId, :lineItemType, " +
                ":modelId, :modelInfo, :modelRegistry, :originId, :paperNo, :questionId, :sorItemAttributionId, " +
                ":rootPipelineId, :score, :sorQuestion, :stage, :status, :synonymId, :tenantId, :vqaScore, :isEncrypted, :encryptionPolicyId, :encryptionPolicy, :sorContainerInstance, :createdOn, :lastUpdatedOn" +
                ")";


        jdbi.useHandle(handle -> {
            var batch = handle.prepareBatch(sql);

            for (MultiValueOutputResult output : outputs) {
                batch.bindBean(output)
                        .bind("createdOn", java.time.LocalDateTime.now())
                        .bind("lastUpdatedOn", java.time.LocalDateTime.now())
                        .add();
            }

            batch.execute();
        });
    }


    public String decryptData(MultivalueSorItemHandlingActionInput input, Boolean pipelineEndToEndEncryptionActivator, InticsIntegrity encryption, String finalEncryptionKey) {

        String value = "";
        String scalarAdapterActivator = action.getContext().getOrDefault("scalar.adapter.activator", "false");
        if (pipelineEndToEndEncryptionActivator && "t".equalsIgnoreCase(input.getIsEncrypted())) {
            try {
                if("false".equalsIgnoreCase(scalarAdapterActivator)){
                    log.info("Scalar activator is disabled, running decryption in AES256 mode when decrypting");
                    value = encryption.decrypt(input.getAnswer(), AES_256, finalEncryptionKey);
                }else {
                    log.info("Scalar activator is enabled, running decryption in policy mode when decrypting");
                    value = encryption.decrypt(input.getAnswer(), input.getEncryptionPolicy(), finalEncryptionKey);
                }
                log.debug("Decrypted value for originId={}, sorItemName={}", input.getOriginId(), input.getSorItemName());

            } catch (Exception e) {
                log.error("Decryption failed for originId={}, sorItemName={}: {}", input.getOriginId(), input.getSorItemName(), e.getMessage(), e);
                throw e;
            }
        }else{
            log.info("end to end encryption activator is deactivated");
            log.debug("returning actual value for originId={}, sorItemName={}", input.getOriginId(), input.getSorItemName());
            value = input.getAnswer();
        }
        return value;
    }

    public List<MultiValueOutputResult> encryptData(Map<String, List<MultiValueOutputResult>> inputs,
                                                    Boolean pipelineEndToEndEncryptionActivator,
                                                    InticsIntegrity encryption) {

        AtomicInteger counter = new AtomicInteger(0);
        List<MultiValueOutputResult> finalResult = new ArrayList<>();

        for (Map.Entry<String, List<MultiValueOutputResult>> entry : inputs.entrySet()) {
            String originId = entry.getKey();
            List<MultiValueOutputResult> items = entry.getValue();

            for (MultiValueOutputResult input : items) {
                Integer increment = counter.incrementAndGet();

                // Build encryption key using originId, sorItemName, and counter
                String encryptionKey = input.getOriginId().concat("_").concat(input.getSorItemName());
                String finalEncryptionKey = encryptionKey.concat("_").concat(String.valueOf(increment));

                String scalarAdapterActivator = action.getContext().getOrDefault("scalar.adapter.activator", "false");
                String value = "";

                if (pipelineEndToEndEncryptionActivator && Boolean.TRUE.equals(input.getIsEncrypted())) {
                    try {
                        if ("false".equalsIgnoreCase(scalarAdapterActivator)) {
                            log.info("Scalar activator is disabled, running encryption in AES256 mode");
                            value = encryption.encrypt(input.getAnswer(), AES_256, finalEncryptionKey);
                            input.setAnswer(value);
                        } else {
                            log.info("Scalar activator is enabled, running encryption in policy mode");
                            value = encryption.encrypt(input.getAnswer(), input.getEncryptionPolicy(), finalEncryptionKey);
                            input.setAnswer(value);
                        }
                        log.info("Encrypted concatenated value for originId={}, sorItemName={}", input.getOriginId(), input.getSorItemName());
                    } catch (Exception e) {
                        log.error("Encryption failed for originId={}, sorItemName={}: {}", input.getOriginId(), input.getSorItemName(), e.getMessage(), e);
                        throw e;
                    }
                }
                finalResult.add(input);
            }
        }
        return finalResult;
    }


    public Map<String, List<MultiValueOutputResult>> groupByOriginAndRemoveDuplicateAnswers(List<MultiValueOutputResult> inputList) {

        return inputList.stream()
                .collect(Collectors.groupingBy(
                        item -> item.getOriginId() + "|" + item.getSorItemName(),
                        Collectors.collectingAndThen(
                                Collectors.toList(),
                                list -> {
                                    Set<String> seenAnswers = new HashSet<>();
                                    return list.stream()
                                            .filter(i -> seenAnswers.add(i.getAnswer()))
                                            .collect(Collectors.toList());
                                }
                        )
                ));
    }


    public static class WhitelistEntry {
        private String truthEntity;
        private int priorityLevel;

        public String getTruthEntity() { return truthEntity; }
        public int getPriorityLevel() { return priorityLevel; }
    }


}
