package in.handyman.raven.lib;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import in.handyman.raven.exception.HandymanException;
import in.handyman.raven.lambda.access.ResourceAccess;
import in.handyman.raven.lambda.action.ActionExecution;
import in.handyman.raven.lambda.action.IActionExecution;
import in.handyman.raven.lambda.doa.audit.ActionExecutionAudit;
import in.handyman.raven.lib.custom.outbound.dao.MetadataContext;
import in.handyman.raven.lib.custom.outbound.dao.PredictionDTO;
import in.handyman.raven.lib.model.ProductResponseGeneration;
import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;

import in.handyman.raven.util.CommonQueryUtil;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.core.result.ResultIterable;
import org.jdbi.v3.core.statement.PreparedBatch;
import org.jdbi.v3.core.statement.Query;
import org.slf4j.Logger;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

/**
 * Auto Generated By Raven
 */
@ActionExecution(
    actionName = "ProductResponseGeneration"
)
public class ProductResponseGenerationAction implements IActionExecution {
  private final ActionExecutionAudit action;

  private final Logger log;

  private final ProductResponseGeneration productResponseGeneration;

  private final Marker aMarker;

  public ProductResponseGenerationAction(final ActionExecutionAudit action, final Logger log,
      final Object productResponseGeneration) {
    this.productResponseGeneration = (ProductResponseGeneration) productResponseGeneration;
    this.action = action;
    this.log = log;
    this.aMarker = MarkerFactory.getMarker(" ProductResponseGeneration:"+this.productResponseGeneration.getName());
  }

  @Override
  public void execute() throws Exception {
    try {
      final Jdbi jdbi = ResourceAccess.rdbmsJDBIConn(productResponseGeneration.getResourceConn());

      List<PredictionDTO> multivalueConcatenationInputs = new ArrayList<>();
      List<ProductResponseAction.ProductResponseOutputTable> productResponseOutputTables = new ArrayList<>();


      jdbi.useTransaction(handle -> {
        final List<String> formattedQuery = CommonQueryUtil.getFormattedQuery(productResponseGeneration.getQuerySet());
        AtomicInteger i = new AtomicInteger(0);
        for (String sqlToExecute : formattedQuery) {
          log.info(aMarker, "executing  query {} from index {}", sqlToExecute, i.getAndIncrement());
          Query query = handle.createQuery(sqlToExecute);
          ResultIterable<PredictionDTO> resultIterable = query.mapToBean(PredictionDTO.class);
          List<PredictionDTO> processingExecutorInputs = resultIterable.stream().collect(Collectors.toList());
          multivalueConcatenationInputs.addAll(processingExecutorInputs);
          log.info(aMarker, "executed query from index {}", i.get());
        }
      });

      log.info("Product Response generation action total rows returned from the query {}", multivalueConcatenationInputs.size());

      Map<String, List<PredictionDTO>> groupedByOriginId = multivalueConcatenationInputs.stream()
              .collect(Collectors.groupingBy(PredictionDTO::getOriginId));
      ObjectMapper objectMapper = JsonMapper.builder()
              .addModule(new JavaTimeModule())
              .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
              .build();

      groupedByOriginId.forEach((originId, predictionDTOList) -> {
        if(!predictionDTOList.isEmpty()){
          String metadata = predictionDTOList.get(0).getMetadataJson();
          Long groupId = predictionDTOList.get(0).getGroupId();
          Long tenantId = predictionDTOList.get(0).getTenantId();
          String batchId = predictionDTOList.get(0).getBatchId();
          String rootPipelineId = predictionDTOList.get(0).getRootPipelineId();
          String transactionId = predictionDTOList.get(0).getTransactionId();

          try {
            JsonNode productResponseJson = buildProductResponseJson(
                    predictionDTOList,
                    originId,
                    tenantId,
                    groupId,
                    batchId,
                    rootPipelineId,
                    transactionId,
                    metadata,
                    objectMapper
            );

            String productResponseStr = objectMapper.writeValueAsString(productResponseJson);

            // Extract inboundTransactionId from metadata if available
            String inboundTransactionId = extractInboundTransactionId(metadata, objectMapper);

            productResponseOutputTables.add(ProductResponseAction.ProductResponseOutputTable.builder()
                    .processId(Integer.valueOf(rootPipelineId))
                    .groupId(groupId)
                    .productResponse(productResponseStr)
                    .originId(originId)
                    .tenantId(tenantId)
                    .rootPipelineId(Long.valueOf(rootPipelineId))
                    .status("COMPLETED")
                    .stage("Product Response Generation")
                    .message("Product Response generated successfully")
                    .triggeredUrl("")
                    .feature("Product")
                    .batchId(batchId)
                    .inboundTransactionId(inboundTransactionId)
                    .createdOn(LocalDateTime.now())
                    .lastUpdatedOn(LocalDateTime.now())
                    .build());
          } catch (Exception e) {
            log.error(aMarker, "Error building product response for originId: {}", originId, e);
            throw new RuntimeException(e);
          }

        }
      });

      //Batch insert into the output table
      executeBatchInsert(jdbi, productResponseOutputTables);
      log.info(aMarker, "Product Response generation Action has been completed {}  ", productResponseGeneration.getName());

    } catch (Exception e) {
      action.getContext().put(productResponseGeneration.getName() + ".isSuccessful", "false");
      log.error(aMarker, "Error in execute method for Multi value concatenation ", e);
      HandymanException handymanException = new HandymanException(e);
      HandymanException.insertException("Multi value concatenation failed ", handymanException, action);
    }



  }

  /**
   * Builds product response JSON structure similar to DocumentInfo from ResponseService
   */
  private JsonNode buildProductResponseJson(
          List<PredictionDTO> predictions,
          String originId,
          Long tenantId,
          Long groupId,
          String batchId,
          String rootPipelineId,
          String transactionId,
          String metadataJson,
          ObjectMapper objectMapper) throws JsonProcessingException {

    log.info(aMarker, "Building product response JSON for originId: {}, predictions: {}", originId, predictions.size());

    ObjectNode documentInfo = objectMapper.createObjectNode();

    // Basic document info - matching the provided JSON structure
    documentInfo.put("originId", originId);

    // Parse metadata if available
    MetadataContext metadataContext = null;
    // Initialize extension and totalProcessedDuration with default values
    documentInfo.put("extension", "");
    documentInfo.put("totalProcessedDuration", 0);

    if (metadataJson != null && !metadataJson.trim().isEmpty()) {
      try {
        metadataContext = objectMapper.readValue(metadataJson, MetadataContext.class);
        if (metadataContext != null) {
          if (metadataContext.getDocumentId() != null) {
            documentInfo.put("documentId", metadataContext.getDocumentId());
          }
          if (metadataContext.getProcessStartTime() != null) {
            documentInfo.put("processStartedOn", metadataContext.getProcessStartTime());
          }
          if (metadataContext.getProcessEndTime() != null) {
            documentInfo.put("processCompletedOn", metadataContext.getProcessEndTime());
          }
          // Always set extension (empty string if not available)
          documentInfo.put("extension", metadataContext.getDocumentExtension() != null ?
                  metadataContext.getDocumentExtension() : "");
          // Calculate totalProcessedDuration if both times are available
          if (metadataContext.getProcessStartTime() != null && metadataContext.getProcessEndTime() != null) {
            try {
              LocalDateTime startTime = LocalDateTime.parse(metadataContext.getProcessStartTime());
              LocalDateTime endTime = LocalDateTime.parse(metadataContext.getProcessEndTime());
              long durationSeconds = Duration.between(startTime, endTime).getSeconds();
              documentInfo.put("totalProcessedDuration", (int)durationSeconds);
            } catch (Exception e) {
              log.warn(aMarker, "Failed to calculate totalProcessedDuration", e);
              documentInfo.put("totalProcessedDuration", 0);
            }
          }
        }
      } catch (Exception e) {
        log.warn(aMarker, "Failed to parse metadata JSON for originId: {}", originId, e);
        // Extension and totalProcessedDuration already set to defaults above
      }
    }

    // Set sourceFileURI and preprocessedFileURI (can be constructed from config or metadata)
    Map<String, String> context = action != null && action.getContext() != null ? action.getContext() : new HashMap<>();
    String sourceFileURI = constructSourceFileURI(originId, tenantId, metadataContext, context);
    String preprocessedFileURI = constructPreprocessedFileURI(originId, tenantId, metadataContext, context);
    documentInfo.put("sourceFileURI", sourceFileURI != null ? sourceFileURI : "");
    documentInfo.put("preprocessedFileURI", preprocessedFileURI != null ? preprocessedFileURI : "");

    // Group predictions by page (paperNo)
    Map<Integer, List<PredictionDTO>> predictionsByPage = predictions.stream()
            .filter(p -> p.getPaperNo() != null)
            .collect(Collectors.groupingBy(
                    PredictionDTO::getPaperNo,
                    LinkedHashMap::new,
                    Collectors.toList()
            ));

    // Calculate total pages
    int totalPages = predictionsByPage.isEmpty() ? 0 :
            predictionsByPage.keySet().stream().mapToInt(Integer::intValue).max().orElse(0);
    documentInfo.put("totalPages", totalPages);

    // Build paperInfo list
    ArrayNode paperInfoArray = objectMapper.createArrayNode();

    predictionsByPage.forEach((pageNo, pagePredictions) -> {
      ObjectNode paperInfo = buildPaperInfo(pageNo, pagePredictions, originId, tenantId, objectMapper);
      paperInfoArray.add(paperInfo);
    });

    documentInfo.set("paperInfo", paperInfoArray);

    // Build summary sections (KVP, Currency, Table, Bulletin, Paragraph)
    buildSummarySections(predictions, documentInfo, objectMapper);

    log.info(aMarker, "Completed building product response JSON for originId: {}", originId);
    return documentInfo;
  }

  /**
   * Builds PaperInfo JSON for a specific page
   */
  private ObjectNode buildPaperInfo(
          Integer pageNo,
          List<PredictionDTO> pagePredictions,
          String originId,
          Long tenantId,
          ObjectMapper objectMapper) {

    ObjectNode paperInfo = objectMapper.createObjectNode();
    paperInfo.put("pageNo", pageNo);
    // paperType can be null - will be set if available from paper classification
    paperInfo.putNull("paperType");

    // Group predictions by feature
    Map<String, List<PredictionDTO>> predictionsByFeature = pagePredictions.stream()
            .filter(p -> p.getFeature() != null)
            .collect(Collectors.groupingBy(PredictionDTO::getFeature));

    ObjectNode featureInfo = objectMapper.createObjectNode();

    // Initialize all feature fields as null - will be set if data exists
    featureInfo.putNull("kie");
    featureInfo.putNull("checkbox");
    featureInfo.putNull("table");
    featureInfo.putNull("currency");
    featureInfo.putNull("bulletin");
    featureInfo.putNull("paragraph");
    featureInfo.putNull("aggregatedTableResult");

    // Build feature-specific data
    predictionsByFeature.forEach((feature, featurePredictions) -> {
      switch (feature.toUpperCase()) {
        case "KIE":
          buildKieFeature(featureInfo, featurePredictions, objectMapper);
          break;
        case "CHECKBOX_EXTRACTION":
        case "CHECKBOX_DETECT":
          buildCheckboxFeature(featureInfo, featurePredictions, objectMapper);
          break;
        case "TABLE_EXTRACT":
        case "TABLE_DETECT":
          buildTableFeature(featureInfo, featurePredictions, objectMapper);
          break;
        case "CURRENCY_DETECTION":
          buildCurrencyFeature(featureInfo, featurePredictions, objectMapper);
          break;
        case "BULLETIN_EXTRACTION":
          buildBulletinFeature(featureInfo, featurePredictions, objectMapper);
          break;
        case "PARAGRAPH_EXTRACTION":
          buildParagraphFeature(featureInfo, featurePredictions, objectMapper);
          break;
        case "TABLE_EXTRACT_AGGREGATE":
          buildTableAggregateFeature(featureInfo, featurePredictions, objectMapper);
          break;
      }
    });

    paperInfo.set("featureInfo", featureInfo);
    return paperInfo;
  }

  /**
   * Builds KIE feature data
   */
  private void buildKieFeature(ObjectNode featureInfo, List<PredictionDTO> predictions, ObjectMapper objectMapper) {
    if (predictions == null || predictions.isEmpty()) {
      return;
    }
    ObjectNode kie = objectMapper.createObjectNode();
    PredictionDTO firstPrediction = predictions.get(0);
    // Always set originId, tenantId, and pageNo (even if null) to match JSON structure
    kie.put("originId", firstPrediction.getOriginId() != null ? firstPrediction.getOriginId() : "");
    kie.put("tenantId", firstPrediction.getTenantId() != null ? firstPrediction.getTenantId() : 0L);
    kie.put("pageNo", firstPrediction.getPaperNo() != null ? firstPrediction.getPaperNo() : 0);

    // Group by container
    Map<String, List<PredictionDTO>> byContainer = predictions.stream()
            .filter(p -> p.getContainerName() != null)
            .collect(Collectors.groupingBy(PredictionDTO::getContainerName));

    ObjectNode entityDetails = objectMapper.createObjectNode();
    ObjectNode sorContainerDetails = objectMapper.createObjectNode();

    byContainer.forEach((containerName, containerPredictions) -> {
      ObjectNode sorContainer = objectMapper.createObjectNode();
      sorContainer.put("sorContainerName", containerName.replace(" ", "_"));
      sorContainer.put("naturalKey", containerName);
      sorContainer.put("originId", predictions.get(0).getOriginId());
      sorContainer.put("tenantId", predictions.get(0).getTenantId());
      sorContainer.put("pageNo", predictions.get(0).getPaperNo());

      ObjectNode sorItemsDetails = objectMapper.createObjectNode();

      containerPredictions.forEach(prediction -> {
        if (prediction.getSorItemName() != null) {
          ObjectNode sorItem = objectMapper.createObjectNode();
          sorItem.put("sorItemName", prediction.getSorItemName().replace(" ", "_"));
          sorItem.put("naturalKey", prediction.getSorItemName());
          sorItem.put("predictedValue", prediction.getPredictedValue() != null ? prediction.getPredictedValue() : "");
          sorItem.put("confidenceScore", prediction.getPrecision() != null ?
                  (int)(prediction.getPrecision() * 100) : 0);
          sorItem.put("originId", prediction.getOriginId());
          sorItem.put("tenantId", prediction.getTenantId());
          sorItem.put("pageNo", prediction.getPaperNo());
          sorItem.putNull("paperType"); // paperType can be null

          // Add bounding box if available, otherwise set to null
          if (prediction.getLeftPos() != null && prediction.getRightPos() != null &&
                  prediction.getUpperPos() != null && prediction.getLowerPos() != null &&
                  (prediction.getLeftPos() != 0.0 || prediction.getRightPos() != 0.0 ||
                          prediction.getUpperPos() != 0.0 || prediction.getLowerPos() != 0.0)) {
            ObjectNode boundingBox = objectMapper.createObjectNode();
            boundingBox.put("leftPosition", prediction.getLeftPos());
            boundingBox.put("rightPosition", prediction.getRightPos());
            boundingBox.put("upperPosition", prediction.getUpperPos());
            boundingBox.put("lowerPosition", prediction.getLowerPos());
            sorItem.set("boundingBox", boundingBox);
          } else {
            sorItem.putNull("boundingBox");
          }

          sorItemsDetails.set(prediction.getSorItemName().replace(" ", "_"), sorItem);
        }
      });

      // Set sorItemsDetails - can be null if empty
      if (sorItemsDetails.size() > 0) {
        sorContainer.set("sorItemsDetails", sorItemsDetails);
      } else {
        sorContainer.putNull("sorItemsDetails");
      }
      sorContainerDetails.set(containerName.replace(" ", "_"), sorContainer);
    });

    entityDetails.set("sorContainerDetails", sorContainerDetails);
    kie.set("entityDetails", entityDetails);
    featureInfo.set("kie", kie);
  }

  /**
   * Builds Checkbox feature data
   */
  private void buildCheckboxFeature(ObjectNode featureInfo, List<PredictionDTO> predictions, ObjectMapper objectMapper) {
    ObjectNode checkbox = objectMapper.createObjectNode();
    checkbox.put("originId", predictions.get(0).getOriginId());
    checkbox.put("tenantId", predictions.get(0).getTenantId());
    checkbox.put("pageNo", predictions.get(0).getPaperNo());

    ArrayNode checkboxItems = objectMapper.createArrayNode();

    predictions.forEach(prediction -> {
      ObjectNode checkboxItem = objectMapper.createObjectNode();
      checkboxItem.put("originId", prediction.getOriginId());
      checkboxItem.put("tenantId", prediction.getTenantId());
      checkboxItem.put("predictedValue", prediction.getPredictedValue() != null ? prediction.getPredictedValue() : "");
      checkboxItem.put("confidenceScore", prediction.getPrecision() != null ?
              (int)(prediction.getPrecision() * 100) : 0);
      checkboxItem.put("checkboxState", prediction.getState() != null ? prediction.getState() : "");
      checkboxItem.put("pageNo", prediction.getPaperNo());

      if (prediction.getLeftPos() != null && prediction.getRightPos() != null &&
              prediction.getUpperPos() != null && prediction.getLowerPos() != null) {
        ObjectNode boundingBox = objectMapper.createObjectNode();
        boundingBox.put("leftPosition", prediction.getLeftPos());
        boundingBox.put("rightPosition", prediction.getRightPos());
        boundingBox.put("upperPosition", prediction.getUpperPos());
        boundingBox.put("lowerPosition", prediction.getLowerPos());
        checkboxItem.set("boundingBox", boundingBox);
      }

      checkboxItems.add(checkboxItem);
    });

    checkbox.set("checkboxItems", checkboxItems);
    featureInfo.set("checkbox", checkbox);
  }

  /**
   * Builds Table feature data
   */
  private void buildTableFeature(ObjectNode featureInfo, List<PredictionDTO> predictions, ObjectMapper objectMapper) {
    ObjectNode table = objectMapper.createObjectNode();
    table.put("originId", predictions.get(0).getOriginId());
    table.put("tenantId", predictions.get(0).getTenantId());
    table.put("pageNo", predictions.get(0).getPaperNo());

    ArrayNode tableDataArray = objectMapper.createArrayNode();

    predictions.forEach(prediction -> {
      if (prediction.getTableData() != null && !prediction.getTableData().trim().isEmpty()) {
        try {
          ObjectNode tableData = objectMapper.createObjectNode();
          tableData.put("originId", prediction.getOriginId());
          tableData.put("tenantId", prediction.getTenantId());
          tableData.put("pageNo", prediction.getPaperNo());
          tableData.put("csvFilePath", prediction.getCsvFilePath() != null ? prediction.getCsvFilePath() : "");

          // Parse table data JSON if available
          JsonNode tableDataJson = objectMapper.readTree(prediction.getTableData());
          if (tableDataJson.has("columnHeaders")) {
            tableData.set("columnHeaders", tableDataJson.get("columnHeaders"));
          }
          if (tableDataJson.has("data")) {
            tableData.set("rowData", tableDataJson.get("data"));
          }

          tableDataArray.add(tableData);
        } catch (Exception e) {
          log.warn(aMarker, "Failed to parse table data for prediction: {}", prediction.getPredictionId(), e);
        }
      }
    });

    table.set("tableData", tableDataArray);
    featureInfo.set("table", table);
  }

  /**
   * Builds Currency feature data
   */
  private void buildCurrencyFeature(ObjectNode featureInfo, List<PredictionDTO> predictions, ObjectMapper objectMapper) {
    ArrayNode currencyArray = objectMapper.createArrayNode();

    predictions.forEach(prediction -> {
      ObjectNode currencyNode = objectMapper.createObjectNode();
      currencyNode.put("currency", prediction.getCurrencyValue() != null ? prediction.getCurrencyValue() : "");
      currencyNode.put("asciiValue", prediction.getCurrencyAsciiValue() != null ? prediction.getCurrencyAsciiValue() : "");
      currencyNode.put("confidenceScore", prediction.getPrecision() != null ?
              (int)(prediction.getPrecision() * 100) : 0);
      currencyArray.add(currencyNode);
    });

    featureInfo.set("currency", currencyArray);
  }

  /**
   * Builds Bulletin feature data
   */
  private void buildBulletinFeature(ObjectNode featureInfo, List<PredictionDTO> predictions, ObjectMapper objectMapper) {
    ArrayNode bulletinArray = objectMapper.createArrayNode();

    predictions.forEach(prediction -> {
      ObjectNode bulletinNode = objectMapper.createObjectNode();
      bulletinNode.put("bulletinHeader", prediction.getBulletinSection() != null ? prediction.getBulletinSection() : "");
      bulletinNode.put("bulletinPoints", prediction.getBulletinPoints() != null ? prediction.getBulletinPoints() : "");
      bulletinArray.add(bulletinNode);
    });

    featureInfo.set("bulletin", bulletinArray);
  }

  /**
   * Builds Paragraph feature data
   */
  private void buildParagraphFeature(ObjectNode featureInfo, List<PredictionDTO> predictions, ObjectMapper objectMapper) {
    ArrayNode paragraphArray = objectMapper.createArrayNode();

    predictions.forEach(prediction -> {
      if (prediction.getSorItemName() != null) {
        ObjectNode paragraphNode = objectMapper.createObjectNode();
        ObjectNode innerMap = objectMapper.createObjectNode();
        innerMap.put("paragraphHeader", prediction.getParagraphSection() != null ? prediction.getParagraphSection() : "");
        innerMap.put("paragraphPoints", prediction.getParagraphPoints() != null ? prediction.getParagraphPoints() : "");
        paragraphNode.set(prediction.getSorItemName(), innerMap);
        paragraphArray.add(paragraphNode);
      }
    });

    featureInfo.set("paragraph", paragraphArray);
  }

  /**
   * Builds Table Aggregate feature data
   */
  private void buildTableAggregateFeature(ObjectNode featureInfo, List<PredictionDTO> predictions, ObjectMapper objectMapper) {
    ArrayNode aggregateArray = objectMapper.createArrayNode();

    predictions.forEach(prediction -> {
      if (prediction.getAggregatedJson() != null && !prediction.getAggregatedJson().trim().isEmpty()) {
        try {
          ObjectNode aggregateData = objectMapper.createObjectNode();
          aggregateData.put("originId", prediction.getOriginId());
          aggregateData.put("tenantId", prediction.getTenantId());
          aggregateData.put("sorItemName", prediction.getSorItemName() != null ? prediction.getSorItemName() : "");
          aggregateData.put("pageNo", prediction.getPaperNo());
          aggregateData.put("sorContainerName", prediction.getContainerName() != null ? prediction.getContainerName() : "");

          JsonNode aggregatedJson = objectMapper.readTree(prediction.getAggregatedJson());
          aggregateData.set("aggregatedjson", aggregatedJson);

          aggregateArray.add(aggregateData);
        } catch (Exception e) {
          log.warn(aMarker, "Failed to parse aggregated JSON for prediction: {}", prediction.getPredictionId(), e);
        }
      }
    });

    featureInfo.set("aggregatedTableResult", aggregateArray);
  }

  /**
   * Builds summary sections (KVP, Currency, Table, Bulletin, Paragraph)
   */
  private void buildSummarySections(List<PredictionDTO> allPredictions, ObjectNode documentInfo, ObjectMapper objectMapper) {
    // KVP Summary - group by container
    ObjectNode kvpSummary = objectMapper.createObjectNode();
    Map<String, List<PredictionDTO>> kvpPredictions = allPredictions.stream()
            .filter(p -> "KIE".equalsIgnoreCase(p.getFeature()) && p.getContainerName() != null)
            .collect(Collectors.groupingBy(PredictionDTO::getContainerName));

    kvpPredictions.forEach((containerName, predictions) -> {
      ObjectNode containerNode = objectMapper.createObjectNode();
      predictions.forEach(prediction -> {
        if (prediction.getSorItemName() != null) {
          String value = prediction.getPredictedValue();
          // Use null for empty strings to match the expected JSON structure
          if (value != null && !value.trim().isEmpty()) {
            containerNode.put(prediction.getSorItemName(), value);
          } else {
            containerNode.putNull(prediction.getSorItemName());
          }
        }
      });
      kvpSummary.set(containerName, containerNode);
    });
    documentInfo.set("kvpSummary", kvpSummary);

    // KVP Confidence Score Summary - group by container with confidence scores
    ObjectNode kvpCfScoreSummary = objectMapper.createObjectNode();
    kvpPredictions.forEach((containerName, predictions) -> {
      ObjectNode containerNode = objectMapper.createObjectNode();
      predictions.forEach(prediction -> {
        if (prediction.getSorItemName() != null) {
          if (prediction.getPrecision() != null) {
            containerNode.put(prediction.getSorItemName(), (int)(prediction.getPrecision() * 100));
          } else {
            containerNode.putNull(prediction.getSorItemName());
          }
        }
      });
      kvpCfScoreSummary.set(containerName, containerNode);
    });
    documentInfo.set("kvpCfScoreSummary", kvpCfScoreSummary);

    // Table Data Summary - empty array for now (can be populated if table data is available)
    ArrayNode tableDataSummary = objectMapper.createArrayNode();
    documentInfo.set("tableDataSummary", tableDataSummary);

    // Currency Summary
    ArrayNode currencySummary = objectMapper.createArrayNode();
    allPredictions.stream()
            .filter(p -> "CURRENCY_DETECTION".equalsIgnoreCase(p.getFeature()))
            .forEach(prediction -> {
              ObjectNode currencyNode = objectMapper.createObjectNode();
              currencyNode.put("currency", prediction.getCurrencyValue() != null ? prediction.getCurrencyValue() : "");
              currencyNode.put("asciiValue", prediction.getCurrencyAsciiValue() != null ? prediction.getCurrencyAsciiValue() : "");
              currencyNode.put("confidenceScore", prediction.getPrecision() != null ?
                      (int)(prediction.getPrecision() * 100) : 0);
              currencySummary.add(currencyNode);
            });
    documentInfo.set("currencySummary", currencySummary);

    // Bulletin Summary
    ArrayNode bulletinSummary = objectMapper.createArrayNode();
    allPredictions.stream()
            .filter(p -> "BULLETIN_EXTRACTION".equalsIgnoreCase(p.getFeature()))
            .forEach(prediction -> {
              ObjectNode bulletinNode = objectMapper.createObjectNode();
              bulletinNode.put("bulletinHeader", prediction.getBulletinSection() != null ? prediction.getBulletinSection() : "");
              bulletinNode.put("bulletinPoints", prediction.getBulletinPoints() != null ? prediction.getBulletinPoints() : "");
              bulletinSummary.add(bulletinNode);
            });
    documentInfo.set("bulletinSummary", bulletinSummary);

    // Paragraph Summary
    ArrayNode paragraphSummary = objectMapper.createArrayNode();
    allPredictions.stream()
            .filter(p -> "PARAGRAPH_EXTRACTION".equalsIgnoreCase(p.getFeature()))
            .forEach(prediction -> {
              if (prediction.getSorItemName() != null) {
                ObjectNode paragraphNode = objectMapper.createObjectNode();
                ObjectNode innerMap = objectMapper.createObjectNode();
                innerMap.put("paragraphHeader", prediction.getParagraphSection() != null ? prediction.getParagraphSection() : "");
                innerMap.put("paragraphPoints", prediction.getParagraphPoints() != null ? prediction.getParagraphPoints() : "");
                paragraphNode.set(prediction.getSorItemName(), innerMap);
                paragraphSummary.add(paragraphNode);
              }
            });
    documentInfo.set("paragraphSummary", paragraphSummary);
  }

  /**
   * Constructs source file URI
   */
  private String constructSourceFileURI(String originId, Long tenantId, MetadataContext metadataContext, Map<String, String> context) {
    if (context == null) {
      context = new HashMap<>();
    }
    String alchemyBaseURL = context.getOrDefault("alchemy.base.url", "");
    String outboundFileUriFormat = context.getOrDefault("outbound.file.uri.format.specifer", "api");

    if ("file".equals(outboundFileUriFormat) && metadataContext != null &&
            metadataContext.getInboundDocumentName() != null && metadataContext.getTransactionId() != null) {
      // Construct file path based on metadata
      return alchemyBaseURL + "/alchemy/vulcan_data/data/output/" + tenantId + "/transaction/" +
              metadataContext.getTransactionId() + "/" + metadataContext.getInboundDocumentName();
    } else {
      // Use API endpoint format
      if (tenantId != null) {
        String tenantIdParam = "?tenantId=" + tenantId;
        return alchemyBaseURL + "/response/file/source/" + originId + tenantIdParam;
      } else {
        return alchemyBaseURL + "/response/file/source/" + originId;
      }
    }
  }

  /**
   * Constructs preprocessed file URI
   */
  private String constructPreprocessedFileURI(String originId, Long tenantId, MetadataContext metadataContext, Map<String, String> context) {
    if (context == null) {
      context = new HashMap<>();
    }
    String alchemyBaseURL = context.getOrDefault("alchemy.base.url", "");
    String outboundFileUriFormat = context.getOrDefault("outbound.file.uri.format.specifer", "api");

    if ("file".equals(outboundFileUriFormat)) {
      // For file format, preprocessed file URI might be empty or constructed differently
      return "";
    } else {
      // Use API endpoint format
      if (tenantId != null) {
        String tenantIdParam = "?tenantId=" + tenantId;
        return alchemyBaseURL + "/response/file/preprocessed/" + originId + tenantIdParam;
      } else {
        return alchemyBaseURL + "/response/file/preprocessed/" + originId;
      }
    }
  }

  /**
   * Extracts inboundTransactionId from metadata JSON
   */
  private String extractInboundTransactionId(String metadataJson, ObjectMapper objectMapper) {
    if (metadataJson == null || metadataJson.trim().isEmpty()) {
      return null;
    }
    try {
      MetadataContext metadataContext = objectMapper.readValue(metadataJson, MetadataContext.class);
      return metadataContext.getInboundTransactionId();
    } catch (Exception e) {
      log.warn(aMarker, "Failed to extract inboundTransactionId from metadata", e);
      return null;
    }
  }

  private void executeBatchInsert(Jdbi jdbi, List<ProductResponseAction.ProductResponseOutputTable> rows) {

    if (rows == null || rows.isEmpty()) {
      log.warn(aMarker, "No rows to insert into {}", productResponseGeneration.getResultTable());
      return;
    }

    final String insertQuery =
            "INSERT INTO " + productResponseGeneration.getResultTable() +
                    " (process_id, group_id, origin_id, product_response, tenant_id, root_pipeline_id, " +
                    " status, stage, message, feature, triggered_url, batch_id, inbound_transaction_id, " +
                    " created_on, last_updated_on) " +
                    " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    jdbi.useTransaction(handle -> {
      try (PreparedBatch batch = handle.prepareBatch(insertQuery)) {

        for (ProductResponseAction.ProductResponseOutputTable row : rows) {
          batch
                  .bind(0, row.getProcessId())
                  .bind(1, row.getGroupId())
                  .bind(2, row.getOriginId())
                  .bind(3, row.getProductResponse())   // TEXT / JSON / JSONB safe
                  .bind(4, row.getTenantId())
                  .bind(5, row.getRootPipelineId())
                  .bind(6, row.getStatus())
                  .bind(7, row.getStage())
                  .bind(8, row.getMessage())
                  .bind(9, row.getFeature())
                  .bind(10, row.getTriggeredUrl())
                  .bind(11, row.getBatchId())
                  .bind(12, row.getInboundTransactionId())
                  .bind(13, row.getCreatedOn())
                  .bind(14, row.getLastUpdatedOn())
                  .add();
        }

        int[] counts = batch.execute();
        log.info(
                aMarker,
                "Batch inserted {} records into {}",
                counts.length,
                productResponseGeneration.getResultTable()
        );

      } catch (Exception e) {
        log.error(aMarker, "Batch insert failed for {}", productResponseGeneration.getResultTable(), e);
        HandymanException handymanException = new HandymanException(e);
        HandymanException.insertException("Batch insert failed for " + productResponseGeneration.getResultTable(), handymanException, action);
      }
    });
  }


  @Override
  public boolean executeIf() throws Exception {
    return productResponseGeneration.getCondition();
  }

  @AllArgsConstructor
  @Data
  @Builder
  public static class ProductResponseOutputTable {

    private Integer processId;
    private Long groupId;
    private String productResponse;
    private String originId;
    private Long tenantId;
    private Long rootPipelineId;
    private String status;
    private String stage;
    private String message;
    private String triggeredUrl;
    private String feature;
    private String batchId;
    private String inboundTransactionId;
    private LocalDateTime createdOn;
    private LocalDateTime lastUpdatedOn;


  }

}
