package in.handyman.raven.lib;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import in.handyman.raven.core.encryption.SecurityEngine;
import in.handyman.raven.core.encryption.impl.EncryptionRequestClass;
import in.handyman.raven.core.encryption.inticsgrity.InticsIntegrity;
import in.handyman.raven.exception.HandymanException;
import in.handyman.raven.lambda.access.ResourceAccess;
import in.handyman.raven.lambda.action.ActionExecution;
import in.handyman.raven.lambda.action.IActionExecution;
import in.handyman.raven.lambda.doa.audit.ActionExecutionAudit;
import in.handyman.raven.lib.adapters.selections.models.SelectionFilteringInputTable;
import in.handyman.raven.lib.adapters.selections.models.WhitelistLabelConfig;
import in.handyman.raven.lib.adapters.selections.models.WhitelistSectionPriority;
import in.handyman.raven.lib.model.SectionFiltering;
import in.handyman.raven.util.CommonQueryUtil;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.core.argument.Arguments;
import org.jdbi.v3.core.argument.NullArgument;
import org.jdbi.v3.core.result.ResultIterable;
import org.jdbi.v3.core.statement.PreparedBatch;
import org.jdbi.v3.core.statement.Query;
import org.slf4j.Logger;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

import java.sql.Types;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;

import static in.handyman.raven.core.enums.EncryptionConstants.ENCRYPT_ITEM_WISE_ENCRYPTION;
import static in.handyman.raven.core.enums.EncryptionConstants.KVP_JSON_PARSER_ENCRYPTION;

/**
 * Auto Generated By Raven
 */
@ActionExecution(actionName = "SectionFiltering")
public class SectionFilteringAction implements IActionExecution {
    public static final String AES_256 = "AES256";
    private final ActionExecutionAudit action;

    private final Logger log;

    private final SectionFiltering sectionFiltering;

    private final Marker aMarker;

    public static final String INSERT_INTO = "INSERT INTO ";
    public static final String INSERT_COLUMNS_UPDATED = "created_on, created_user_id, last_updated_on, last_updated_user_id, tenant_id, group_id, "
            +
            "root_pipeline_id, batch_id, model_registry, sor_container_id, sor_container_name, " +
            "sor_item_name, sor_item_label, section_alias, answer, confidence, bbox, " +
            "bbox_asis, paper_no, origin_id, extracted_image_unit, image_dpi, image_height, " +
            "image_width, is_label_matching, label_match_message, " +
            " is_encrypted, encryption_policy, sor_container_instance";

    public static final String INSERT_INTO_VALUES_UPDATED = "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?," +
            "?, ?, ?, ?, ?, ?, ?, ?, ?, ?," +
            " ?, ?, ?, ?, ?, ?, ?::boolean, ?, ?)";

    private final ObjectMapper objectMapper = new ObjectMapper();

    public SectionFilteringAction(final ActionExecutionAudit action, final Logger log,
            final Object sectionFiltering) {
        this.sectionFiltering = (SectionFiltering) sectionFiltering;
        this.action = action;
        this.log = log;
        this.aMarker = MarkerFactory.getMarker(" SectionFiltering:" + this.sectionFiltering.getName());
    }

    @Override
    public void execute() throws Exception {
        log.info(aMarker, "Section Filtering Action started");

        final Jdbi jdbi = ResourceAccess.rdbmsJDBIConn(sectionFiltering.getResourceConn());
        final InticsIntegrity encryption = SecurityEngine.getInticsIntegrityMethod(action, log);
        jdbi.getConfig(Arguments.class).setUntypedNullArgument(new NullArgument(Types.NULL));

        // 1 Fetch data
        List<SelectionFilteringInputTable> tableInfos = getDataFromSelectQuery(jdbi);
        log.info(aMarker, "Total records fetched from input query: {}", tableInfos.size());

        // 2 Decrypt values
        if (action.getContext().get(ENCRYPT_ITEM_WISE_ENCRYPTION).equals("true")) {
            decryptAnswers(tableInfos, encryption);
            if (action.getContext().get(KVP_JSON_PARSER_ENCRYPTION).equals("true")) {
                decryptLabels(tableInfos, encryption);
                decryptSectionAlias(tableInfos, encryption);
            }
        }
        log.info(aMarker, "Decryption completed for fetched records {}", tableInfos.size());

        // 3 Process Filtering Logic
        List<SelectionFilteringInputTable> processedTableInfos = processFiltering(tableInfos);
        log.info(aMarker, "Filtering completed. Final count: {}", processedTableInfos.size());

        // 4 Encrypt results before persistence or outbound
        if (action.getContext().get(ENCRYPT_ITEM_WISE_ENCRYPTION).equals("true")) {
            encryptAnswers(processedTableInfos, encryption);
            if (action.getContext().get(KVP_JSON_PARSER_ENCRYPTION).equals("true")) {
                encryptLabels(processedTableInfos, encryption);
                encryptSectionAlias(processedTableInfos, encryption);
            }
        }

        // 5 Prepare output rows
        executeBatchInsert(jdbi, processedTableInfos);

        log.info(aMarker, "Section Filtering Action completed successfully.");
    }

    // Package-private for testing
    List<SelectionFilteringInputTable> processFiltering(List<SelectionFilteringInputTable> inputList) {
        if (inputList == null || inputList.isEmpty()) {
            return Collections.emptyList();
        }

        // Group by OriginId + SorContainerName
        Map<String, Map<String, List<SelectionFilteringInputTable>>> grouped = inputList.stream()
                .collect(Collectors.groupingBy(
                        row -> row.getOriginId() != null ? row.getOriginId() : "NULL",
                        Collectors.groupingBy(
                                row -> row.getSorContainerName() != null ? row.getSorContainerName() : "NULL")));

        List<SelectionFilteringInputTable> finalResult = new ArrayList<>();

        for (Map<String, List<SelectionFilteringInputTable>> containerMap : grouped.values()) {
            for (List<SelectionFilteringInputTable> groupRows : containerMap.values()) {
                finalResult.addAll(processGroup(groupRows));
            }
        }

        return finalResult;
    }

    private List<SelectionFilteringInputTable> processGroup(List<SelectionFilteringInputTable> rows) {
        if (rows.isEmpty())
            return rows;

        List<AnnotatedRow> annotatedRows = new ArrayList<>();

        for (SelectionFilteringInputTable row : rows) {
            AnnotatedRow annotated = new AnnotatedRow(row);

            // 1. Blacklist Check
            Set<String> blacklistedLabels = splitCsvToSet(row.getBlacklistedLabels());
            Set<String> blacklistedSections = splitCsvToSet(row.getBlacklistedSections());
            String cleanLabel = removeSpecialCharacters(row.getSorItemLabel());
            String cleanSection = removeSpecialCharacters(row.getSectionAlias());

            boolean isBlacklisted = false;

            if (cleanLabel != null && blacklistedLabels.contains(cleanLabel)) {
                annotated.messages.add("Blacklisted Label match: " + cleanLabel);
                isBlacklisted = true;
            }
            if (cleanSection != null && blacklistedSections.contains(cleanSection)) {
                annotated.messages.add("Blacklisted Section match: " + cleanSection);
                isBlacklisted = true;
            }

            if (isBlacklisted) {
                annotated.isBlacklisted = true;
                row.setLabelMatching(false);
                row.setLabelMatchMessage("Filtered out by blacklist.");
            } else {
                // 2. Whitelist Priority Check
                // Whitelist config might be null/empty
                List<WhitelistLabelConfig> wlLabels = parseWhitelistConfig(row.getWhitelistedLabels(), objectMapper);
                List<WhitelistSectionPriority> wlSections = parseWhiteListSectionWithPriority(
                        row.getWhitelistedSectionsWithPriority(), objectMapper);

                int priority = Integer.MAX_VALUE;
                boolean isWhitelisted = false;

                // Check Labels (Priority 1 if matched)
                if (cleanLabel != null) {
                    for (WhitelistLabelConfig config : wlLabels) {
                        String wlKey = removeSpecialCharacters(config.getWhitelistKey());
                        if (wlKey != null && wlKey.equals(cleanLabel)) {
                            priority = 1; // Highest priority
                            isWhitelisted = true;
                            annotated.messages.add("Whitelisted Label match: " + cleanLabel);
                            break;
                        }
                    }
                }

                // Check Sections (Use configured priority)
                if (cleanSection != null) {
                    for (WhitelistSectionPriority config : wlSections) {
                        String wlKey = removeSpecialCharacters(config.getWhitelistKey());
                        if (wlKey != null && wlKey.equals(cleanSection)) {
                            // If we already have a label match (p=1), we keep it unless section priority is
                            // somehow better (unlikely if 1 is max)
                            // Assuming matches both -> take the better one.
                            if (config.getSectionPriority() != null && config.getSectionPriority() < priority) {
                                priority = config.getSectionPriority();
                                annotated.messages
                                        .add("Whitelisted Section match: " + cleanSection + " (p=" + priority + ")");
                            }
                            isWhitelisted = true;
                        }
                    }
                }

                annotated.priority = priority;
                annotated.isWhitelisted = isWhitelisted;
            }
            annotatedRows.add(annotated);
        }

        // 3. Selection Logic
        // "at last the output will be like each originId, sorContainerName will be
        // having an single node which is the prioritized by whitelisted if nothing
        // matched then return everything"

        // Filter to only non-blacklisted items that have a whitelist match
        List<AnnotatedRow> candidates = annotatedRows.stream()
                .filter(ar -> !ar.isBlacklisted && ar.isWhitelisted)
                .collect(Collectors.toList());

        if (candidates.isEmpty()) {
            // "if nothing matched then return everything"
            // Ensure we return everything.
            return rows.stream().peek(r -> {
                // Determine if it was blacklisted, preserve that info?
                // If returning everything, we still want to show if it was blacklisted?
                // User said "nothing matched" referring to Whitelist.
                // But if they were explicitly blacklisted, maybe we shouldn't return them as
                // 'valid'?
                // However, the prompt says "return everything", let's strict to that.
                if (!r.isLabelMatching()
                        && (r.getLabelMatchMessage() != null && r.getLabelMatchMessage().contains("blacklist"))) {
                    // keep as false
                } else {
                    r.setLabelMatching(true);
                    r.setLabelMatchMessage("Returned (No whitelist matches found in group).");
                }
            }).collect(Collectors.toList());
        } else {
            // Whitelist matches found. Pick the winner.
            // Sort by Priority (ASC) -> Confidence (DESC) -> ID (ASC)
            candidates.sort(Comparator.comparingInt((AnnotatedRow ar) -> ar.priority)
                    .thenComparing(ar -> ar.row.getConfidence() != null ? parseConfidence(ar.row.getConfidence()) : 0.0,
                            Comparator.reverseOrder())
                    .thenComparing(ar -> ar.row.getId() != null ? ar.row.getId() : Long.MAX_VALUE));

            AnnotatedRow winner = candidates.get(0);
            winner.row.setLabelMatching(true);
            winner.row.setLabelMatchMessage(
                    "Selected Winner (p=" + winner.priority + "). " + String.join(" | ", winner.messages));
            winner.row.setLabelPriorityIdx(String.valueOf(winner.priority));

            return Collections.singletonList(winner.row);
        }
    }

    private double parseConfidence(String conf) {
        try {
            return Double.parseDouble(conf);
        } catch (NumberFormatException e) {
            return 0.0;
        }
    }

    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    private static class AnnotatedRow {
        SelectionFilteringInputTable row;
        boolean isBlacklisted = false;
        boolean isWhitelisted = false;
        int priority = Integer.MAX_VALUE;
        List<String> messages = new ArrayList<>();

        public AnnotatedRow(SelectionFilteringInputTable row) {
            this.row = row;
        }
    }

    // ================= HELPER METHODS (Copied/Adapted) =================

    private static Set<String> splitCsvToSet(String csv) {
        if (csv == null || csv.isBlank()) {
            return Collections.emptySet();
        }
        return Arrays.stream(csv.split(","))
                .map(String::trim)
                .filter(s -> !s.isEmpty())
                .map(SectionFilteringAction::removeSpecialCharacters) // normalize
                .collect(Collectors.toSet());
    }

    private static List<WhitelistLabelConfig> parseWhitelistConfig(String jsonConfig, ObjectMapper objectMapper) {
        try {
            if (jsonConfig == null || jsonConfig.isBlank()) {
                return Collections.emptyList();
            }
            return Arrays.asList(objectMapper.readValue(jsonConfig, WhitelistLabelConfig[].class));
        } catch (Exception e) {
            return Collections.emptyList();
        }
    }

    public List<WhitelistSectionPriority> parseWhiteListSectionWithPriority(
            String whitelistedSectionsWithPriority,
            ObjectMapper objectMapper) {

        if (whitelistedSectionsWithPriority == null
                || whitelistedSectionsWithPriority.trim().isEmpty()) {
            return List.of();
        }

        try {
            // Handle cases where JSON is stored as stringified JSON
            String json = whitelistedSectionsWithPriority.trim();

            // If accidentally wrapped in quotes
            if ((json.startsWith("\"") && json.endsWith("\""))
                    || (json.startsWith("'") && json.endsWith("'"))) {
                json = objectMapper.readValue(json, String.class);
            }

            return objectMapper.readValue(
                    json,
                    new TypeReference<List<WhitelistSectionPriority>>() {
                    });

        } catch (Exception e) {
            log.warn(aMarker, "Failed to parse whitelistedSectionsWithPriority. Input={}",
                    whitelistedSectionsWithPriority, e);
            return List.of();
        }
    }

    private static String removeSpecialCharacters(String input) {
        if (input == null)
            return null;
        return input.replaceAll("[^a-zA-Z0-9]", "").toLowerCase().trim();
    }

    private void executeBatchInsert(Jdbi jdbi, List<SelectionFilteringInputTable> rows) {
        if (rows.isEmpty())
            return;

        String insertQuery = INSERT_INTO + sectionFiltering.getOutputTable() +
                " ( " + INSERT_COLUMNS_UPDATED + " ) " + INSERT_INTO_VALUES_UPDATED;

        jdbi.useHandle(handle -> {
            try (PreparedBatch batch = handle.prepareBatch(insertQuery)) {

                rows.forEach(row -> {
                    batch.bind(0, row.getCreatedOn())
                            .bind(1, row.getCreatedUserId())
                            .bind(2, row.getLastUpdatedOn())
                            .bind(3, row.getLastUpdatedUserId())
                            .bind(4, row.getTenantId())
                            .bind(5, row.getGroupId())
                            .bind(6, row.getRootPipelineId())
                            .bind(7, row.getBatchId())
                            .bind(8, row.getModelRegistry())
                            .bind(9, row.getSorContainerId())
                            .bind(10, row.getSorContainerName())
                            .bind(11, row.getSorItemName())
                            .bind(12, row.getSorItemLabel())
                            .bind(13, row.getSectionAlias())
                            .bind(14, row.getAnswer())
                            .bind(15, row.getConfidence())
                            .bind(16, row.getBbox())
                            .bind(17, row.getBboxAsIs())
                            .bind(18, row.getPaperNo())
                            .bind(19, row.getOriginId())
                            .bind(20, row.getExtractedImageUnit())
                            .bind(21, row.getImageDpi())
                            .bind(22, row.getImageHeight())
                            .bind(23, row.getImageWidth())
                            .bind(24, row.isLabelMatching())
                            .bind(25, row.getLabelMatchMessage())
                            .bind(26, row.getIsEncrypted())
                            .bind(27, row.getEncryptionPolicy())
                            .bind(28, row.getSorContainerInstance());

                    batch.add();
                });

                int[] counts = batch.execute();
                log.info(aMarker, "Batch inserted {} records into {}", counts.length,
                        sectionFiltering.getOutputTable());

            } catch (Exception e) {
                log.error(aMarker, "Batch insert failed for {}", sectionFiltering.getOutputTable(), e);
                HandymanException.insertException(
                        "Error in batch insert into " + sectionFiltering.getOutputTable(),
                        new HandymanException(e),
                        action);
            }
        });
    }

    private List<SelectionFilteringInputTable> getDataFromSelectQuery(Jdbi jdbi) {
        List<SelectionFilteringInputTable> tableInfos = new ArrayList<>();
        jdbi.useTransaction(handle -> {
            final List<String> formattedQuery = CommonQueryUtil.getFormattedQuery(sectionFiltering.getQuerySet());
            AtomicInteger i = new AtomicInteger(0);
            formattedQuery.forEach(sqlToExecute -> {
                log.info(aMarker, "executing  query {} from index {}", sqlToExecute, i.getAndIncrement());
                Query query = handle.createQuery(sqlToExecute);
                ResultIterable<SelectionFilteringInputTable> resultIterable = query
                        .mapToBean(SelectionFilteringInputTable.class);
                List<SelectionFilteringInputTable> detailList = resultIterable.stream().collect(Collectors.toList());
                tableInfos.addAll(detailList);
                log.info(aMarker, "executed query from index {}", i.get());
            });
        });
        log.info("Query set executed and returned entities size: {}", tableInfos.size());
        return tableInfos;
    }

    public void decryptAnswers(List<SelectionFilteringInputTable> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream()
                .filter(SelectionFilteringInputTable::getIsEncrypted)
                .filter(obj -> obj.getId() != null && obj.getAnswer() != null && !obj.getAnswer().isEmpty())
                .map(obj -> new EncryptionRequestClass(AES_256, obj.getAnswer(), String.valueOf(obj.getId())))
                .collect(Collectors.toList());
        log.info(aMarker, "Total records to decrypt for answers: {}", encryptionRequests.size());
        // Step 2: Call external Protegrity API
        List<EncryptionRequestClass> responseList = encryption.decrypt(encryptionRequests);

        // Step 3: Build a lookup map from response
        Map<Long, String> encryptedMap = responseList.stream()
                .filter(item -> item.getKey() != null && item.getKey().matches("\\d+"))
                .collect(Collectors.toMap(
                        item -> Long.parseLong(item.getKey()),
                        EncryptionRequestClass::getValue));

        // Step 4: Update original list
        for (SelectionFilteringInputTable item : inputList) {
            if (item.getId() != null && encryptedMap.containsKey(item.getId())) {
                String answer = encryptedMap.get(item.getId());
                item.setAnswer(answer);

            }
        }
    }

    public void decryptLabels(List<SelectionFilteringInputTable> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream()
                .filter(obj -> obj.getId() != null && obj.getSorItemLabel() != null && !obj.getSorItemLabel().isEmpty())
                .map(obj -> new EncryptionRequestClass(AES_256, obj.getSorItemLabel(), String.valueOf(obj.getId())))
                .collect(Collectors.toList());
        log.info(aMarker, "Total records to decrypt for labels: {}", encryptionRequests.size());
        // Step 2: Call external Protegrity API
        List<EncryptionRequestClass> responseList = encryption.decrypt(encryptionRequests);

        // Step 3: Build a lookup map from response
        Map<Long, String> encryptedMap = responseList.stream()
                .filter(item -> item.getKey() != null && item.getKey().matches("\\d+"))
                .collect(Collectors.toMap(
                        item -> Long.parseLong(item.getKey()),
                        EncryptionRequestClass::getValue));

        // Step 4: Update original list
        for (SelectionFilteringInputTable item : inputList) {
            if (item.getId() != null && encryptedMap.containsKey(item.getId())) {
                String label = encryptedMap.get(item.getId());
                item.setSorItemLabel(label);

            }
        }
    }

    public void encryptAnswers(List<SelectionFilteringInputTable> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream()
                .filter(SelectionFilteringInputTable::getIsEncrypted)
                .filter(obj -> obj.getId() != null && obj.getAnswer() != null && !obj.getAnswer().isEmpty())
                .map(obj -> new EncryptionRequestClass(AES_256, obj.getAnswer(), String.valueOf(obj.getId())))
                .collect(Collectors.toList());
        log.info(aMarker, "Total records to encrypt for answers: {}", encryptionRequests.size());
        // Step 2: Call external Protegrity API
        List<EncryptionRequestClass> responseList = encryption.encrypt(encryptionRequests);

        // Step 3: Build a lookup map from response
        Map<Long, String> encryptedMap = responseList.stream()
                .filter(item -> item.getKey() != null && item.getKey().matches("\\d+"))
                .collect(Collectors.toMap(
                        item -> Long.parseLong(item.getKey()),
                        EncryptionRequestClass::getValue));

        // Step 4: Update original list
        for (SelectionFilteringInputTable item : inputList) {
            if (item.getId() != null && encryptedMap.containsKey(item.getId())) {
                item.setAnswer(encryptedMap.get(item.getId()));
            }
        }
    }

    public void encryptLabels(List<SelectionFilteringInputTable> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream()
                .filter(obj -> obj.getId() != null && obj.getSorItemLabel() != null && !obj.getSorItemLabel().isEmpty())
                .map(obj -> new EncryptionRequestClass(AES_256, obj.getSorItemLabel(), String.valueOf(obj.getId())))
                .collect(Collectors.toList());
        log.info(aMarker, "Total records to encrypt for Labels: {}", encryptionRequests.size());
        // Step 2: Call external Protegrity API
        List<EncryptionRequestClass> responseList = encryption.encrypt(encryptionRequests);

        // Step 3: Build a lookup map from response
        Map<Long, String> encryptedMap = responseList.stream()
                .filter(item -> item.getKey() != null && item.getKey().matches("\\d+"))
                .collect(Collectors.toMap(
                        item -> Long.parseLong(item.getKey()),
                        EncryptionRequestClass::getValue));

        // Step 4: Update original list
        for (SelectionFilteringInputTable item : inputList) {
            if (item.getId() != null && encryptedMap.containsKey(item.getId())) {
                item.setSorItemLabel(encryptedMap.get(item.getId()));
            }
        }
    }

    public void encryptSectionAlias(List<SelectionFilteringInputTable> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream()
                .filter(obj -> obj.getId() != null && obj.getSectionAlias() != null && !obj.getSectionAlias().isEmpty())
                .map(obj -> new EncryptionRequestClass(AES_256, obj.getSectionAlias(), String.valueOf(obj.getId())))
                .collect(Collectors.toList());
        log.info(aMarker, "Total records to encrypt for section alias: {}", encryptionRequests.size());
        // Step 2: Call external Protegrity API
        List<EncryptionRequestClass> responseList = encryption.encrypt(encryptionRequests);

        // Step 3: Build a lookup map from response
        Map<Long, String> encryptedMap = responseList.stream()
                .filter(item -> item.getKey() != null && item.getKey().matches("\\d+"))
                .collect(Collectors.toMap(
                        item -> Long.parseLong(item.getKey()),
                        EncryptionRequestClass::getValue));

        // Step 4: Update original list
        for (SelectionFilteringInputTable item : inputList) {
            if (item.getId() != null && encryptedMap.containsKey(item.getId())) {
                item.setSectionAlias(encryptedMap.get(item.getId()));
            }
        }
    }

    public void decryptSectionAlias(List<SelectionFilteringInputTable> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream()
                .filter(obj -> obj.getId() != null && obj.getSectionAlias() != null
                        && !obj.getSectionAlias().equals(""))
                .map(obj -> new EncryptionRequestClass(AES_256, obj.getSectionAlias(), String.valueOf(obj.getId())))
                .collect(Collectors.toList());
        log.info(aMarker, "Total records to decrypt for section alias: {}", encryptionRequests.size());
        // Step 2: Call external Protegrity API
        List<EncryptionRequestClass> responseList = encryption.decrypt(encryptionRequests);

        // Step 3: Build a lookup map from response
        Map<Long, String> encryptedMap = responseList.stream()
                .filter(item -> item.getKey() != null && item.getKey().matches("\\d+"))
                .collect(Collectors.toMap(
                        item -> Long.parseLong(item.getKey()),
                        EncryptionRequestClass::getValue));

        // Step 4: Update original list
        for (SelectionFilteringInputTable item : inputList) {
            if (item.getId() != null && encryptedMap.containsKey(item.getId())) {
                String answer = encryptedMap.get(item.getId());
                item.setSectionAlias(answer);

            }
        }
    }

    @Override
    public boolean executeIf() throws Exception {
        return sectionFiltering.getCondition();
    }
}
