package in.handyman.raven.lib;

import com.fasterxml.jackson.databind.ObjectMapper;
import in.handyman.raven.core.encryption.SecurityEngine;
import in.handyman.raven.core.encryption.impl.EncryptionRequestClass;
import in.handyman.raven.core.encryption.inticsgrity.InticsIntegrity;
import in.handyman.raven.exception.HandymanException;
import in.handyman.raven.lambda.access.ResourceAccess;
import in.handyman.raven.lambda.action.ActionExecution;
import in.handyman.raven.lambda.action.IActionExecution;
import in.handyman.raven.lambda.doa.audit.ActionExecutionAudit;
import in.handyman.raven.lib.adapters.selections.ExtractedField;
import in.handyman.raven.lib.adapters.selections.FieldSelectionAdapter;
import in.handyman.raven.lib.adapters.selections.FieldSelectionAdapterFactory;
import in.handyman.raven.lib.adapters.selections.LabelWithPriorityProcessor;
import in.handyman.raven.lib.adapters.selections.models.AggregationEvaluatorInputModel;
import in.handyman.raven.lib.adapters.selections.models.SelectionFilteringInputTable;
import in.handyman.raven.lib.model.SectionFilteringAfterGrouping;

import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;

import in.handyman.raven.util.CommonQueryUtil;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.core.argument.Arguments;
import org.jdbi.v3.core.argument.NullArgument;
import org.jdbi.v3.core.result.ResultIterable;
import org.jdbi.v3.core.statement.PreparedBatch;
import org.jdbi.v3.core.statement.Query;
import org.slf4j.Logger;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

import static in.handyman.raven.core.enums.EncryptionConstants.ENCRYPT_ITEM_WISE_ENCRYPTION;
import static in.handyman.raven.core.enums.EncryptionConstants.KVP_JSON_PARSER_ENCRYPTION;

/**
 * Auto Generated By Raven
 */
@ActionExecution(actionName = "SectionFilteringAfterGrouping")
public class SectionFilteringAfterGroupingAction implements IActionExecution {
    private final ActionExecutionAudit action;

    private final Logger log;

    private final SectionFilteringAfterGrouping sectionFilteringAfterGrouping;

    private final Marker aMarker;

    public static final String INSERT_INTO = "INSERT INTO ";
    public static final String INSERT_COLUMNS_UPDATED = "created_on, created_user_id, last_updated_on, last_updated_user_id, tenant_id, group_id, " + "root_pipeline_id, batch_id, model_registry, sor_container_id, sor_container_name, sor_container_instance, " + "sor_item_name, sor_item_label, section_alias, answer, confidence, bbox, bbox_asis, " + "paper_no, origin_id, extracted_image_unit, image_dpi, image_height, image_width, " + "is_label_matching, label_match_message, is_encrypted, encryption_policy, " + "aggregated_score, masked_score, predicted_value, vqa_score, rank, " + "sor_item_attribution_id, document_id, acc_transaction_id, b_box, frequency, " + "question_id, synonym_id, status, version, " + "model_registry_id, category";


    public static final String INSERT_INTO_VALUES_UPDATED = "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, " + "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, " + "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, " + "?, ?, ?, ?, ?)";

    public static final String AES_256 = "AES256";
    public static final String SECTION_FILTERING_LABEL_WITH_PRIORITY = "section.filtering.label.with.priority";

    public SectionFilteringAfterGroupingAction(final ActionExecutionAudit action, final Logger log, final Object sectionFilteringAfterGrouping) {
        this.sectionFilteringAfterGrouping = (SectionFilteringAfterGrouping) sectionFilteringAfterGrouping;
        this.action = action;
        this.log = log;
        this.aMarker = MarkerFactory.getMarker(" SectionFilteringAfterGrouping:" + this.sectionFilteringAfterGrouping.getName());
    }

    @Override
    public void execute() throws Exception {
        log.info(aMarker, "Section Filtering Action started");

        final Jdbi jdbi = ResourceAccess.rdbmsJDBIConn(sectionFilteringAfterGrouping.getResourceConn());
        final InticsIntegrity encryption = SecurityEngine.getInticsIntegrityMethod(action, log);
        jdbi.getConfig(Arguments.class).setUntypedNullArgument(new NullArgument(Types.NULL));
        ObjectMapper objectMapper = new ObjectMapper();
        LabelWithPriorityProcessor LabelWithPriorityProcessor = new LabelWithPriorityProcessor(objectMapper, log);

        // 1 Fetch data
        List<AggregationEvaluatorInputModel> tableInfos = getDataFromSelectQuery(jdbi);
        log.info(aMarker, "Total records fetched from input query: {}", tableInfos.size());

        // 2 Decrypt values
        if (action.getContext().get(ENCRYPT_ITEM_WISE_ENCRYPTION).equals("true")) {
            decryptAnswers(tableInfos, encryption);
            if (action.getContext().get(KVP_JSON_PARSER_ENCRYPTION).equals("true")) {
//        decryptLabels(tableInfos, encryption);
                decryptSectionAlias(tableInfos, encryption);
            }

        }


        // 4 Pre-filter summary
        log.debug(aMarker, "Pre-filter Extracted Fields count: {}", tableInfos.size());
        LabelWithPriorityProcessor labelWithPriorityProcessor = new LabelWithPriorityProcessor(objectMapper, log);

        List<AggregationEvaluatorInputModel> updatedTableInfos = new ArrayList<>(labelWithPriorityProcessor.process(tableInfos));
        log.debug(aMarker, "After-filter Extracted Fields count: {}", tableInfos.size());

        // 7 Encrypt results before persistence or outbound
        if (action.getContext().get(ENCRYPT_ITEM_WISE_ENCRYPTION).equals("true")) {
            encryptAnswers(updatedTableInfos, encryption);
            if (action.getContext().get(KVP_JSON_PARSER_ENCRYPTION).equals("true")) {
//        encryptLabels(updatedTableInfos, encryption);
                encryptSectionAlias(updatedTableInfos, encryption);
            }

        }

        // 8 Prepare output rows
        log.info(aMarker, "Total records to be inserted before filtering: {}", updatedTableInfos.size());
        executeBatchInsert(jdbi, updatedTableInfos);

        log.info(aMarker, "Section Filtering Action completed successfully.");
    }

    private void executeBatchInsert(Jdbi jdbi, List<AggregationEvaluatorInputModel> rows) {

        String insertQuery = INSERT_INTO + sectionFilteringAfterGrouping.getOutputTable() + " ( " + INSERT_COLUMNS_UPDATED + " ) " + INSERT_INTO_VALUES_UPDATED;

        jdbi.useHandle(handle -> {
            try (PreparedBatch batch = handle.prepareBatch(insertQuery)) {

                rows.forEach(row -> {
                    batch.bind(0, row.getCreatedOn()).bind(1, row.getCreatedUserId()).bind(2, row.getLastUpdatedOn()).bind(3, row.getLastUpdatedUserId()).bind(4, row.getTenantId()).bind(5, row.getGroupId()).bind(6, row.getRootPipelineId()).bind(7, row.getBatchId()).bind(8, row.getModelRegistry()).bind(9, row.getSorContainerId()).bind(10, row.getSorContainerName()).bind(11, row.getSorContainerInstance())

                            .bind(12, row.getSorItemName()).bind(13, "").bind(14, row.getSectionAlias()).bind(15, row.getAnswer()).bind(16, row.getScore()).bind(17, row.getBBox()).bind(18, row.getBBox()).bind(19, row.getPaperNo()).bind(20, row.getOriginId()).bind(21, row.getExtractedImageUnit()).bind(22, row.getImageDpi()).bind(23, row.getImageHeight()).bind(24, row.getImageWidth()).bind(25, row.isLabelMatching()).bind(26, row.getLabelMatchMessage()).bind(27, row.getIsEncrypted()).bind(28, row.getEncryptionPolicy())

                            // ---- aggregation_evaluator_output extra fields (NULL-safe) ----
                            .bind(29, row.getVqaScore())  // aggregated_score
                            .bind(30, row.getVqaScore())  // masked_score
                            .bind(31, row.getAnswer())  // predicted_value
                            .bind(32, row.getVqaScore())  // vqa_score
                            .bind(33, 1)  // rank
                            .bind(34, 6)  // sor_item_attribution_id
                            .bind(35, "")  // document_id
                            .bind(36, 1)  // acc_transaction_id
                            .bind(37, row.getBBox())  // b_box
                            .bind(38, 1)  // frequency
                            .bind(39, row.getQuestionId())  // question_id
                            .bind(40, row.getSynonymId())  // synonym_id
                            .bind(41, "ACTIVE")  // status
                            .bind(42, 1)  // version
                            .bind(43, row.getModelId())  // model_registry_id
                            .bind(44, row.getCategory()); // category

                    batch.add();
                });

                int[] counts = batch.execute();
                log.info(aMarker, "Batch inserted {} records into {}", counts.length, sectionFilteringAfterGrouping.getOutputTable());

            } catch (Exception e) {
                log.error(aMarker, "Batch insert failed for {}", sectionFilteringAfterGrouping.getOutputTable(), e);
                HandymanException.insertException("Error in batch insert into " + sectionFilteringAfterGrouping.getOutputTable(), new HandymanException(e), action);
            }
        });
    }


    private List<AggregationEvaluatorInputModel> getDataFromSelectQuery(Jdbi jdbi) {
        List<AggregationEvaluatorInputModel> tableInfos = new ArrayList<>();
        jdbi.useTransaction(handle -> {
            final List<String> formattedQuery = CommonQueryUtil.getFormattedQuery(sectionFilteringAfterGrouping.getQuerySet());
            AtomicInteger i = new AtomicInteger(0);
            formattedQuery.forEach(sqlToExecute -> {
                log.info(aMarker, "executing  query {} from index {}", sqlToExecute, i.getAndIncrement());
                Query query = handle.createQuery(sqlToExecute);
                ResultIterable<AggregationEvaluatorInputModel> resultIterable = query.mapToBean(AggregationEvaluatorInputModel.class);
                List<AggregationEvaluatorInputModel> detailList = resultIterable.stream().collect(Collectors.toList());
                tableInfos.addAll(detailList);
                log.info(aMarker, "executed query from index {}", i.get());
            });
        });
        log.info("Query set executed and returned entities size: {}", tableInfos.size());
        return tableInfos;
    }

    public void decryptAnswers(List<AggregationEvaluatorInputModel> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream().filter(AggregationEvaluatorInputModel::getIsEncrypted).filter(obj -> obj.getId() != null && obj.getAnswer() != null && !obj.getAnswer().isEmpty()).map(obj -> new EncryptionRequestClass(AES_256, obj.getAnswer(), String.valueOf(obj.getId()))).collect(Collectors.toList());
        log.info(aMarker, "Total records to decrypt for answers: {}", encryptionRequests.size());
        // Step 2: Call external Protegrity API
        List<EncryptionRequestClass> responseList = encryption.decrypt(encryptionRequests);

        // Step 3: Build a lookup map from response
        Map<Long, String> encryptedMap = responseList.stream().filter(item -> item.getKey() != null && item.getKey().matches("\\d+")).collect(Collectors.toMap(item -> Long.parseLong(item.getKey()), EncryptionRequestClass::getValue));


        // Step 4: Update original list
        for (AggregationEvaluatorInputModel item : inputList) {
            if (item.getId() != null && encryptedMap.containsKey(item.getId())) {
                String answer = encryptedMap.get(item.getId());
                item.setAnswer(answer);

            }
        }
    }

    public void encryptAnswers(List<AggregationEvaluatorInputModel> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream().filter(AggregationEvaluatorInputModel::getIsEncrypted).filter(obj -> obj.getId() != null && obj.getAnswer() != null && !obj.getAnswer().isEmpty()).map(obj -> new EncryptionRequestClass(AES_256, obj.getAnswer(), String.valueOf(obj.getId()))).collect(Collectors.toList());
        log.info(aMarker, "Total records to encrypt for answers: {}", encryptionRequests.size());
        // Step 2: Call external Protegrity API
        List<EncryptionRequestClass> responseList = encryption.encrypt(encryptionRequests);

        // Step 3: Build a lookup map from response
        Map<Long, String> encryptedMap = responseList.stream().filter(item -> item.getKey() != null && item.getKey().matches("\\d+")).collect(Collectors.toMap(item -> Long.parseLong(item.getKey()), EncryptionRequestClass::getValue));


        // Step 4: Update original list
        for (AggregationEvaluatorInputModel item : inputList) {
            if (item.getId() != null && encryptedMap.containsKey(item.getId())) {
                item.setAnswer(encryptedMap.get(item.getId()));
            }
        }
    }

    public void encryptSectionAlias(List<AggregationEvaluatorInputModel> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream().filter(obj -> obj.getId() != null && obj.getSectionAlias() != null && !obj.getSectionAlias().isEmpty()).map(obj -> new EncryptionRequestClass(AES_256, obj.getSectionAlias(), String.valueOf(obj.getId()))).collect(Collectors.toList());
        log.info(aMarker, "Total records to encrypt for section alias: {}", encryptionRequests.size());
        // Step 2: Call external Protegrity API
        List<EncryptionRequestClass> responseList = encryption.encrypt(encryptionRequests);

        // Step 3: Build a lookup map from response
        Map<Long, String> encryptedMap = responseList.stream().filter(item -> item.getKey() != null && item.getKey().matches("\\d+")).collect(Collectors.toMap(item -> Long.parseLong(item.getKey()), EncryptionRequestClass::getValue));


        // Step 4: Update original list
        for (AggregationEvaluatorInputModel item : inputList) {
            if (item.getId() != null && encryptedMap.containsKey(item.getId())) {
                item.setSectionAlias(encryptedMap.get(item.getId()));
            }
        }
    }


    public void decryptSectionAlias(List<AggregationEvaluatorInputModel> inputList, InticsIntegrity encryption) {
        if (inputList == null || inputList.isEmpty()) {
            return;
        }

        // Step 1: Convert to EncryptionRequestClass
        List<EncryptionRequestClass> encryptionRequests = inputList.stream().filter(obj -> obj.getId() != null && obj.getSectionAlias() != null && !obj.getSectionAlias().equals("")).map(obj -> new EncryptionRequestClass(AES_256, obj.getSectionAlias(), String.valueOf(obj.getId()))).collect(Collectors.toList());
        log.info(aMarker, "Total records to decrypt for section alias: {}", encryptionRequests.size());
        // Step 2: Call external Protegrity API
        List<EncryptionRequestClass> responseList = encryption.decrypt(encryptionRequests);

        // Step 3: Build a lookup map from response
        Map<Long, String> encryptedMap = responseList.stream().filter(item -> item.getKey() != null && item.getKey().matches("\\d+")).collect(Collectors.toMap(item -> Long.parseLong(item.getKey()), EncryptionRequestClass::getValue));


        // Step 4: Update original list
        for (AggregationEvaluatorInputModel item : inputList) {
            if (item.getId() != null && encryptedMap.containsKey(item.getId())) {
                String answer = encryptedMap.get(item.getId());
                item.setSectionAlias(answer);

            }
        }
    }


    @Override
    public boolean executeIf() throws Exception {
        return sectionFilteringAfterGrouping.getCondition();
    }
}
