version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  elastic.store:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elastic.store
    environment:
      - node.name=elastic.store
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elastic.store
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.audit.enabled=true
      - ELASTIC_PASSWORD=password
      - ELASTICSEARCH_USERNAME=elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: curl -s https://elastic.store:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

  maria_db:
    image: "mariadb"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: handyman_vm
      MYSQL_ROOT_PASSWORD: password

  zio_app_ui:
    image: openjdk:11
    container_name: zio-app-ui
    #    restart: always
    ports:
      - "9000:9000"
    environment:
      TZ: "Asia/Kolkata"
    command: [ 'java', '-jar', '/zio-app-ui.jar' ]


