package in.handyman.raven.lib.alchemy.common;

public enum Feature {
    CLASSIFICATION, KIE, CHECKBOX_DETECT, CHECKBOX_EXTRACTION, TABLE_DETECT, TABLE_EXTRACT, KVP,
    TABLE_EXTRACT_AGGREGATE,CURRENCY_DETECTION,BULLETIN_EXTRACTION,PARAGRAPH_EXTRACTION, FACE_DETECTION, FIGURE_DETECTION

}
