package in.handyman.raven.lib.model.triton;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum PipelineName {

    PAPER_ITEMIZER("PAPER_ITEMIZER"),
    AUTO_ROTATION("AUTO_ROTATION"),
    GREY_SCALE_CONVERSION("GREY_SCALE_CONVERSION"),
    TEXT_EXTRACTION("TEXT_EXTRACTION"),
    ZERO_SHOT_CLASSIFIER("ZERO_SHOT_CLASSIFIER"),
    PHRASE_MATCH("PHRASE_MATCH"),
    PAPER_CLASSIFICATION("PAPER_CLASSIFICATION"),
    CURRENCY_DETECTION("CURRENCY_DETECTION"),
    QR_EXTRACTION("QR_EXTRACTION"),
    URGENCY_TRIAGE("URGENCY_TRIAGE"),
    VQA_TRANSACTION("VQA_TRANSACTION"),
    TABLE_EXTRACTION("TABLE_EXTRACTION"),
    CONTROL_DATA("CONTROL_DATA_COS"),
    FILE_MERGER("FILE_MERGER"),
    NOISE_DETECTION("NOISE_DETECTION"),
    PARAGRAPH_EXTRACTION("PARAGRAPH_EXTRACTION"),
    BULLETIN_EXTRACTION("BULLETIN_EXTRACTION"),
    FACE_DETECTION("FACE_DETECTION"),
    FIGURE_DETECTION("FIGURE_DETECTION"),
    KRYPTON_KVP_ACTION("KRYPTON_KVP_ACTION"),
    NEON_KVP_ACTION("NEON_KVP_ACTION"),
    RADON_KVP_ACTION("RADON_KVP_ACTION"),
    VALIDATION_LLM("VALIDATION_LLM");

    private final String processName;
}
